# build stage
FROM node:16-alpine as build-stage

WORKDIR /app

COPY package*.json /app/

RUN npm install 

COPY ./ /app/

ARG REACT_APP_HOST
ARG REACT_APP_REPORT_HOST
ARG REACT_APP_REPORT_SOCKET_HOST
ARG REACT_APP_SOCKET_HOST
ARG REACT_APP_WMSX_URL
ARG REACT_APP_MMSX_URL
ARG REACT_APP_QMSX_URL
ARG REACT_APP_SOCKET_NOTIFICATION_HOST
ARG REACT_APP_NOTIFICATION_HOST
ARG REACT_APP_VTI_DOMAIN
ARG REACT_APP_VERSION

ENV REACT_APP_HOST $REACT_APP_HOST
ENV REACT_APP_REPORT_HOST $REACT_APP_REPORT_HOST
ENV REACT_APP_REPORT_SOCKET_HOST $REACT_APP_REPORT_SOCKET_HOST
ENV REACT_APP_SOCKET_HOST $REACT_APP_HOST
ENV REACT_APP_WMSX_URL $REACT_APP_WMSX_URL
ENV REACT_APP_MMSX_URL $REACT_APP_MMSX_URL
ENV REACT_APP_QMSX_URL $REACT_APP_QMSX_URL
ENV REACT_APP_NOTIFICATION_HOST $REACT_APP_NOTIFICATION_HOST
ENV REACT_APP_SOCKET_NOTIFICATION_HOST $REACT_APP_SOCKET_NOTIFICATION_HOST
ENV REACT_APP_VTI_DOMAIN $REACT_APP_VTI_DOMAIN
ENV REACT_APP_VERSION $REACT_APP_VERSION

RUN npm run build:rs

RUN rm -rf /etc/nginx/conf.d

# production stage
FROM nginx:1.17-alpine as production-stage

COPY conf /etc/nginx

COPY --from=build-stage /app/build /usr/share/nginx/html

CMD ["nginx", "-g", "daemon off;"]