export const FUNCTION_CODE = {
  USER_CREATE_USER: 'USER_CREATE_USER',
  USER_UPDATE_USER: 'USER_UPDATE_USER',
  USER_DELETE_USER: 'USER_DELETE_USER',
  USER_DETAIL_USER: 'USER_DETAIL_USER',
  USER_LIST_USER: 'USER_LIST_USER',
  USER_REJECT_USER: 'USER_REJECT_USER',
  USER_CONFIRM_USER: 'USER_CONFIRM_USER',
  USER_EXPORT_USER: 'USER_EXPORT_USER',
  USER_IMPORT_USER: 'USER_IMPORT_USER',
  USER_ACTIVE_USER: 'USER_ACTIVE_USER',
  USER_INACTIVE_USER: 'USER_INACTIVE_USER',
  USER_CHANGE_PASSWORD_USER: 'USER_CHANGE_PASSWORD_USER',
  USER_RESET_PASSWORD_USER: 'USER_RESET_PASSWORD_USER',
  USER_DETAIL_COMPANY: 'USER_DETAIL_COMPANY',
  USER_LIST_COMPANY: 'USER_LIST_COMPANY',
  USER_CREATE_COMPANY: 'USER_CREATE_COMPANY',
  USER_UPDATE_COMPANY: 'USER_UPDATE_COMPANY',
  USER_DELETE_COMPANY: 'USER_DELETE_COMPANY',
  USER_REJECT_COMPANY: 'USER_REJECT_COMPANY',
  USER_CONFIRM_COMPANY: 'USER_CONFIRM_COMPANY',
  USER_CREATE_FACTORY: 'USER_CREATE_FACTORY',
  USER_UPDATE_FACTORY: 'USER_UPDATE_FACTORY',
  USER_DELETE_FACTORY: 'USER_DELETE_FACTORY',
  USER_DETAIL_FACTORY: 'USER_DETAIL_FACTORY',
  USER_LIST_FACTORY: 'USER_LIST_FACTORY',
  USER_CONFIG_SIGNATURE: 'USER_CONFIG_SIGNATURE',
  USER_IMPORT_FACTORY: 'USER_IMPORT_FACTORY',
  USER_MANAGE_USER_PERMISSION: 'USER_MANAGE_USER_PERMISSION',
  USER_CREATE_DEPARTMENT_SETTING: 'USER_CREATE_DEPARTMENT_SETTING',
  USER_UPDATE_DEPARTMENT_SETTING: 'USER_UPDATE_DEPARTMENT_SETTING',
  USER_UPDATE_STATUS_DEPARTMENT_SETTING:
    'USER_UPDATE_STATUS_DEPARTMENT_SETTING',
  USER_DELETE_DEPARTMENT_SETTING: 'USER_DELETE_DEPARTMENT_SETTING',
  USER_DETAIL_DEPARTMENT_SETTING: 'USER_DETAIL_DEPARTMENT_SETTING',
  USER_CONFIRM_DEPARTMENT_SETTING: 'USER_CONFIRM_DEPARTMENT_SETTING',
  USER_REJECT_DEPARTMENT_SETTING: 'USER_REJECT_DEPARTMENT_SETTING',
  USER_LIST_DEPARTMENT_SETTING: 'USER_LIST_DEPARTMENT_SETTING',
  USER_DECENTRALIZATION_PERMISSION_GROUP_DEPARTMENT_SETTING:
    'USER_DECENTRALIZATION_PERMISSION_GROUP_DEPARTMENT_SETTING',
  USER_EXPORT_DEPARTMENT_SETTING: 'USER_EXPORT_DEPARTMENT_SETTING',
  USER_IMPORT_DEPARTMENT_SETTING: 'USER_IMPORT_DEPARTMENT_SETTING',
  USER_UPDATE_PERMISSION_USER_ROLE: 'USER_UPDATE_PERMISSION_USER_ROLE',
  USER_LIST_PERMISSION_USER_ROLE: 'USER_LIST_PERMISSION_USER_ROLE',
  USER_CREATE_DEPARTMENT_RECEIPT: 'USER_CREATE_DEPARTMENT_RECEIPT',
  USER_UPDATE_DEPARTMENT_RECEIPT: 'USER_UPDATE_DEPARTMENT_RECEIPT',
  USER_DELETE_DEPARTMENT_RECEIPT: 'USER_DELETE_DEPARTMENT_RECEIPT',
  USER_DETAIL_DEPARTMENT_RECEIPT: 'USER_DETAIL_DEPARTMENT_RECEIPT',
  ITEM_CREATE_INVENTORY_NORM: 'ITEM_CREATE_INVENTORY_NORM',
  ITEM_UPDATE_INVENTORY_NORM: 'ITEM_UPDATE_INVENTORY_NORM',
  ITEM_DELETE_INVENTORY_NORM: 'ITEM_DELETE_INVENTORY_NORM',
  ITEM_DETAIL_INVENTORY_NORM: 'ITEM_DETAIL_INVENTORY_NORM',
  ITEM_LIST_INVENTORY_NORM: 'ITEM_LIST_INVENTORY_NORM',
  ITEM_CREATE_BLOCK: 'ITEM_CREATE_BLOCK',
  ITEM_UPDATE_BLOCK: 'ITEM_UPDATE_BLOCK',
  ITEM_DELETE_BLOCK: 'ITEM_DELETE_BLOCK',
  ITEM_DETAIL_BLOCK: 'ITEM_DETAIL_BLOCK',
  ITEM_LIST_BLOCK: 'ITEM_LIST_BLOCK',
  ITEM_CREATE_PACKAGE: 'ITEM_CREATE_PACKAGE',
  ITEM_UPDATE_PACKAGE: 'ITEM_UPDATE_PACKAGE',
  ITEM_DELETE_PACKAGE: 'ITEM_DELETE_PACKAGE',
  ITEM_DETAIL_PACKAGE: 'ITEM_DETAIL_PACKAGE',
  ITEM_LIST_PACKAGE: 'ITEM_LIST_PACKAGE',
  ITEM_CREATE_ITEM_DETAIL: 'ITEM_CREATE_ITEM_DETAIL',
  ITEM_UPDATE_ITEM_DETAIL: 'ITEM_UPDATE_ITEM_DETAIL',
  ITEM_DELETE_ITEM_DETAIL: 'ITEM_DELETE_ITEM_DETAIL',
  ITEM_DETAIL_ITEM_DETAIL: 'ITEM_DETAIL_ITEM_DETAIL',
  ITEM_LIST_ITEM_DETAIL: 'ITEM_LIST_ITEM_DETAIL',
  ITEM_CREATE_SUSPEND_ITEM_LOCATION: 'ITEM_CREATE_SUSPEND_ITEM_LOCATION',
  ITEM_CHANGE_STATUS_SUSPEND_ITEM_LOCATION:
    'ITEM_CHANGE_STATUS_SUSPEND_ITEM_LOCATION',
  ITEM_DELETE_SUSPEND_ITEM_LOCATION: 'ITEM_DELETE_SUSPEND_ITEM_LOCATION',
  ITEM_DETAIL_SUSPEND_ITEM_LOCATION: 'ITEM_DETAIL_SUSPEND_ITEM_LOCATION',
  ITEM_LIST_SUSPEND_ITEM_LOCATION: 'ITEM_LIST_SUSPEND_ITEM_LOCATION',
  ITEM_CREATE_PALLET: 'ITEM_CREATE_PALLET',
  ITEM_UPDATE_PALLET: 'ITEM_UPDATE_PALLET',
  ITEM_DELETE_PALLET: 'ITEM_DELETE_PALLET',
  ITEM_DETAIL_PALLET: 'ITEM_DETAIL_PALLET',
  ITEM_LIST_PALLET: 'ITEM_LIST_PALLET',
  ITEM_CONFIRM_PALLET: 'ITEM_CONFIRM_PALLET',
  ITEM_REJECT_PALLET: 'ITEM_REJECT_PALLET',
  ITEM_CREATE_OBJECT_CATEGORY: 'ITEM_CREATE_OBJECT_CATEGORY',
  USER_CONFIRM_DEPARTMENT_RECEIPT: 'USER_CONFIRM_DEPARTMENT_RECEIPT',
  USER_REJECT_DEPARTMENT_RECEIPT: 'USER_REJECT_DEPARTMENT_RECEIPT',
  ITEM_DETAIL_OBJECT_CATEGORY: 'ITEM_DETAIL_OBJECT_CATEGORY',
  ITEM_LIST_OBJECT_CATEGORY: 'ITEM_LIST_OBJECT_CATEGORY',
  USER_LIST_DEPARTMENT_RECEIPT: 'USER_LIST_DEPARTMENT_RECEIPT',
  USER_IMPORT_DEPARTMENT_RECEIPT: 'USER_IMPORT_DEPARTMENT_RECEIPT',
  USER_EXPORT_DEPARTMENT_RECEIPT: 'USER_EXPORT_DEPARTMENT_RECEIPT',

  ITEM_CREATE_REQUEST_ITEM_CODE: 'ITEM_CREATE_REQUEST_ITEM_CODE',
  SALE_CREATE_SALE_ORDER: 'SALE_CREATE_SALE_ORDER',
  SALE_UPDATE_SALE_ORDER: 'SALE_UPDATE_SALE_ORDER',
  SALE_DELETE_SALE_ORDER: 'SALE_DELETE_SALE_ORDER',
  SALE_DETAIL_SALE_ORDER: 'SALE_DETAIL_SALE_ORDER',
  SALE_LIST_SALE_ORDER: 'SALE_LIST_SALE_ORDER',
  SALE_CONFIRM_SALE_ORDER: 'SALE_CONFIRM_SALE_ORDER',
  SALE_REJECT_SALE_ORDER: 'SALE_REJECT_SALE_ORDER',
  SALE_APPROVE_SALE_ORDER: 'SALE_APPROVE_SALE_ORDER',
  SALE_CREATE_VENDOR: 'SALE_CREATE_VENDOR',
  SALE_UPDATE_VENDOR: 'SALE_UPDATE_VENDOR',
  SALE_DETAIL_VENDOR: 'SALE_DETAIL_VENDOR',
  SALE_LIST_VENDOR: 'SALE_LIST_VENDOR',
  SALE_CREATE_PRODUCTION_ORDER: 'SALE_CREATE_PRODUCTION_ORDER',
  SALE_UPDATE_PRODUCTION_ORDER: 'SALE_UPDATE_PRODUCTION_ORDER',
  SALE_DELETE_PRODUCTION_ORDER: 'SALE_DELETE_PRODUCTION_ORDER',
  SALE_DETAIL_PRODUCTION_ORDER: 'SALE_DETAIL_PRODUCTION_ORDER',
  SALE_LIST_PRODUCTION_ORDER: 'SALE_LIST_PRODUCTION_ORDER',
  SALE_CONFIRM_PRODUCTION_ORDER: 'SALE_CONFIRM_PRODUCTION_ORDER',
  SALE_REJECT_PRODUCTION_ORDER: 'SALE_REJECT_PRODUCTION_ORDER',
  SALE_CREATE_PURCHASED_ORDER: 'SALE_CREATE_PURCHASED_ORDER',
  SALE_UPDATE_PURCHASED_ORDER: 'SALE_UPDATE_PURCHASED_ORDER',
  SALE_DELETE_PURCHASED_ORDER: 'SALE_DELETE_PURCHASED_ORDER',
  SALE_DETAIL_PURCHASED_ORDER: 'SALE_DETAIL_PURCHASED_ORDER',
  SALE_LIST_PURCHASED_ORDER: 'SALE_LIST_PURCHASED_ORDER',
  SALE_CONFIRM_PURCHASED_ORDER: 'SALE_CONFIRM_PURCHASED_ORDER',
  SALE_REJECT_PURCHASED_ORDER: 'SALE_REJECT_PURCHASED_ORDER',
  SALE_IMPORT_PURCHASED_ORDER: 'SALE_IMPORT_PURCHASED_ORDER',
  SALE_IMPORT_VENDOR: 'SALE_IMPORT_VENDOR',
  SALE_CONFIRM_VENDOR: 'SALE_CONFIRM_VENDOR',
  SALE_REJECT_VENDOR: 'SALE_REJECT_VENDOR',
  SALE_CREATE_SALE_ORDER_EXPORT: 'SALE_CREATE_SALE_ORDER_EXPORT',
  WAREHOUSE_CREATE_WAREHOUSE: 'WAREHOUSE_CREATE_WAREHOUSE',
  WAREHOUSE_UPDATE_WAREHOUSE: 'WAREHOUSE_UPDATE_WAREHOUSE',
  WAREHOUSE_DETAIL_WAREHOUSE: 'WAREHOUSE_DETAIL_WAREHOUSE',
  WAREHOUSE_LIST_WAREHOUSE: 'WAREHOUSE_LIST_WAREHOUSE',
  WAREHOUSE_CONFIRM_WAREHOUSE: 'WAREHOUSE_CONFIRM_WAREHOUSE',
  WAREHOUSE_REJECT_WAREHOUSE: 'WAREHOUSE_REJECT_WAREHOUSE',
  WAREHOUSE_DELETE_WAREHOUSE: 'WAREHOUSE_DELETE_WAREHOUSE',
  WAREHOUSE_ACTIVE_WAREHOUSE: 'WAREHOUSE_ACTIVE_WAREHOUSE',
  WAREHOUSE_INACTIVE_WAREHOUSE: 'WAREHOUSE_INACTIVE_WAREHOUSE',
  WAREHOUSE_EXPORT_WAREHOUSES: 'WAREHOUSE_EXPORT_WAREHOUSES',
  WAREHOUSE_IMPORT_WAREHOUSES: 'WAREHOUSE_IMPORT_WAREHOUSE',
  SALE_CREATE_IMPORT_ORDER: 'SALE_CREATE_IMPORT_ORDER',
  SALE_UPDATE_IMPORT_ORDER: 'SALE_UPDATE_IMPORT_ORDER',
  SALE_DELETE_IMPORT_ORDER: 'SALE_DELETE_IMPORT_ORDER',
  SALE_DETAIL_IMPORT_ORDER: 'SALE_DETAIL_IMPORT_ORDER',
  SALE_LIST_IMPORT_ORDER: 'SALE_LIST_IMPORT_ORDER',
  SALE_CONFIRM_IMPORT_ORDER: 'SALE_CONFIRM_IMPORT_ORDER',
  SALE_REJECT_IMPORT_ORDER: 'SALE_REJECT_IMPORT_ORDER',
  SALE_APPROVE_IMPORT_ORDER: 'SALE_APPROVE_IMPORT_ORDER',
  SALE_LIST_PURCHASED_ORDER_IMPORT: 'SALE_LIST_PURCHASED_ORDER_IMPORT',
  SALE_DELETE_PURCHASED_ORDER_IMPORT: 'SALE_DELETE_PURCHASED_ORDER_IMPORT',
  SALE_DETAIL_PURCHASED_ORDER_IMPORT: 'SALE_DETAIL_PURCHASED_ORDER_IMPORT',
  SALE_CONFIRM_PURCHASED_ORDER_IMPORT: 'SALE_CONFIRM_PURCHASED_ORDER_IMPORT',
  SALE_REJECT_PURCHASED_ORDER_IMPORT: 'SALE_REJECT_PURCHASED_ORDER_IMPORT',
  SALE_APPROVE_PURCHASED_ORDER_IMPORT: 'SALE_APPROVE_PURCHASED_ORDER_IMPORT',
  SALE_IMPORT_PURCHASED_ORDER_IMPORT: 'SALE_IMPORT_PURCHASED_ORDER_IMPORT',
  SALE_SYNC_PURCHASED_ORDER_IMPORT_TO_EBS:
    'SALE_SYNC_PURCHASED_ORDER_IMPORT_TO_EBS',
  SALE_CREATE_CONSTRUCTION: 'SALE_CREATE_CONSTRUCTION',
  WAREHOUSE_IMPORT_WAREHOUSE_SHELF_FLOOR:
    'WAREHOUSE_IMPORT_WAREHOUSE_SHELF_FLOOR',
  WAREHOUSE_LIST_WAREHOUSE_IMPORT_EXPORT:
    'WAREHOUSE_LIST_WAREHOUSE_IMPORT_EXPORT',
  WAREHOUSE_DETAIL_WAREHOUSE_IMPORT_EXPORT:
    'WAREHOUSE_DETAIL_WAREHOUSE_IMPORT_EXPORT',
  WAREHOUSE_CREATE_INVENTORY: 'WAREHOUSE_CREATE_INVENTORY',
  WAREHOUSE_UPDATE_INVENTORY: 'WAREHOUSE_UPDATE_INVENTORY',
  WAREHOUSE_DELETE_INVENTORY: 'WAREHOUSE_DELETE_INVENTORY',
  SALE_EXPORT_VENDOR: 'SALE_EXPORT_VENDOR',
  SALE_APPROVE_SALE_ORDER_EXPORT: 'SALE_APPROVE_SALE_ORDER_EXPORT',
  SALE_COLLECT_SALE_ORDER_EXPORT: 'SALE_COLLECT_SALE_ORDER_EXPORT',
  SALE_RETURN_SALE_ORDER_EXPORT: 'SALE_RETURN_SALE_ORDER_EXPORT',
  SALE_IMPORT_SALE_ORDER_EXPORT: 'SALE_IMPORT_SALE_ORDER_EXPORT',
  SALE_EXPORT_SALE_ORDER_EXPORT: 'SALE_EXPORT_SALE_ORDER_EXPORT',
  SALE_RECEIVE_PURCHASED_ORDER_IMPORT: 'SALE_RECEIVE_PURCHASED_ORDER_IMPORT',
  SALE_RETURN_PURCHASED_ORDER_IMPORT: 'SALE_RETURN_PURCHASED_ORDER_IMPORT',
  SALE_CREATE_PURCHASED_ORDER_IMPORT_RECEIVE:
    'SALE_CREATE_PURCHASED_ORDER_IMPORT_RECEIVE',
  SALE_EXPORT_PURCHASED_ORDER_IMPORT: 'SALE_EXPORT_PURCHASED_ORDER_IMPORT',
  SALE_IMPORT_CONSTRUCTION: 'SALE_IMPORT_CONSTRUCTION',
  SALE_EXPORT_CONSTRUCTION: 'SALE_EXPORT_CONSTRUCTION',
  SALE_IMPORT_CATEGORY_CONSTRUCTION: 'SALE_IMPORT_CATEGORY_CONSTRUCTION',
  SALE_EXPORT_CATEGORY_CONSTRUCTION: 'SALE_EXPORT_CATEGORY_CONSTRUCTION',
  SALE_DETAIL_RECEIPT: 'SALE_DETAIL_RECEIPT',
  SALE_LIST_RECEIPT: 'SALE_LIST_RECEIPT',
  SALE_RETURN_RECEIPT: 'SALE_RETURN_RECEIPT',
  SALE_UPDATE_SALE_ORDER_EXPORT: 'SALE_UPDATE_SALE_ORDER_EXPORT',
  SALE_CANCEL_SYNC_SALE_ORDER_EXPORT: 'SALE_CANCEL_SYNC_SALE_ORDER_EXPORT',
  SALE_UPDATE_HEADER_SALE_ORDER_EXPORT: 'SALE_UPDATE_HEADER_SALE_ORDER_EXPORT',
  SALE_DELETE_SALE_ORDER_EXPORT: 'SALE_DELETE_SALE_ORDER_EXPORT',
  SALE_DETAIL_SALE_ORDER_EXPORT: 'SALE_DETAIL_SALE_ORDER_EXPORT',
  SALE_LIST_SALE_ORDER_EXPORT: 'SALE_LIST_SALE_ORDER_EXPORT',
  SALE_CONFIRM_SALE_ORDER_EXPORT: 'SALE_CONFIRM_SALE_ORDER_EXPORT',
  SALE_REJECT_SALE_ORDER_EXPORT: 'SALE_REJECT_SALE_ORDER_EXPORT',
  SALE_SYNC_SALE_ORDER_TO_EBS: 'SALE_SYNC_SALE_ORDER_TO_EBS',
  SALE_CREATE_PURCHASED_ORDER_IMPORT: 'SALE_CREATE_PURCHASED_ORDER_IMPORT',
  SALE_UPDATE_PURCHASED_ORDER_IMPORT: 'SALE_UPDATE_PURCHASED_ORDER_IMPORT',
  SALE_UPDATE_HEADER_PURCHASED_ORDER_IMPORT:
    'SALE_UPDATE_HEADER_PURCHASED_ORDER_IMPORT',
  SALE_CANCEL_SYNC_PURCHASED_ORDER_IMPORT:
    'SALE_CANCEL_SYNC_PURCHASED_ORDER_IMPORT',
  SALE_UPDATE_CONSTRUCTION: 'SALE_UPDATE_CONSTRUCTION',
  SALE_DETAIL_CONSTRUCTION: 'SALE_DETAIL_CONSTRUCTION',
  SALE_CONFIRM_CONSTRUCTION: 'SALE_CONFIRM_CONSTRUCTION',
  SALE_REJECT_CONSTRUCTION: 'SALE_REJECT_CONSTRUCTION',
  SALE_LIST_CONSTRUCTION: 'SALE_LIST_CONSTRUCTION',
  SALE_REJECT_CATEGORY_CONSTRUCTION: 'SALE_REJECT_CATEGORY_CONSTRUCTION',
  SALE_CREATE_CATEGORY_CONSTRUCTION: 'SALE_CREATE_CATEGORY_CONSTRUCTION',
  SALE_UPDATE_CATEGORY_CONSTRUCTION: 'SALE_UPDATE_CATEGORY_CONSTRUCTION',
  SALE_DETAIL_CATEGORY_CONSTRUCTION: 'SALE_DETAIL_CATEGORY_CONSTRUCTION',
  SALE_CONFIRM_CATEGORY_CONSTRUCTION: 'SALE_CONFIRM_CATEGORY_CONSTRUCTION',
  SALE_LIST_CATEGORY_CONSTRUCTION: 'SALE_LIST_CATEGORY_CONSTRUCTION',
  WAREHOUSE_DETAIL_INVENTORY: 'WAREHOUSE_DETAIL_INVENTORY',
  WAREHOUSE_LIST_INVENTORY: 'WAREHOUSE_LIST_INVENTORY',
  WAREHOUSE_CONFIRM_INVENTORY: 'WAREHOUSE_CONFIRM_INVENTORY',
  WAREHOUSE_REJECT_INVENTORY: 'WAREHOUSE_REJECT_INVENTORY',
  WAREHOUSE_APPROVE_INVENTORY: 'WAREHOUSE_APPROVE_INVENTORY',
  WAREHOUSE_EXPORT_INVENTORY: 'WAREHOUSE_EXPORT_INVENTORY',

  //request transfer
  REQUEST_CREATE_TRANSFER_REQUEST: 'REQUEST_CREATE_TRANSFER_REQUEST',
  REQUEST_UPDATE_TRANSFER_REQUEST: 'REQUEST_UPDATE_TRANSFER_REQUEST',
  REQUEST_DELETE_TRANSFER_REQUEST: 'REQUEST_DELETE_TRANSFER_REQUEST',
  REQUEST_CONFIRM_TRANSFER_REQUEST: 'REQUEST_CONFIRM_TRANSFER_REQUEST',
  REQUEST_REJECT_TRANSFER_REQUEST: 'REQUEST_REJECT_TRANSFER_REQUEST',
  REQUEST_LIST_TRANSFER_REQUEST: 'REQUEST_LIST_TRANSFER_REQUEST',
  REQUEST_DETAIL_TRANSFER_REQUEST: 'REQUEST_DETAIL_TRANSFER_REQUEST',
  REQUEST_IMPORT_TRANSFER_REQUEST: 'REQUEST_IMPORT_TRANSFER_REQUEST',
  REQUEST_EXPORT_TRANSFER_REQUEST: 'REQUEST_EXPORT_TRANSFER_REQUEST',

  //warehouse transfer
  WAREHOUSE_CREATE_WAREHOUSE_TRANSFER: 'TICKET_CREATE_WAREHOUSE_TRANSFER',
  WAREHOUSE_UPDATE_WAREHOUSE_TRANSFER: 'TICKET_UPDATE_WAREHOUSE_TRANSFER',
  WAREHOUSE_DETAIL_WAREHOUSE_TRANSFER: 'TICKET_DETAIL_WAREHOUSE_TRANSFER',
  WAREHOUSE_LIST_WAREHOUSE_TRANSFER: 'TICKET_LIST_WAREHOUSE_TRANSFER',
  WAREHOUSE_DELETE_WAREHOUSE_TRANSFER: 'TICKET_DELETE_WAREHOUSE_TRANSFER',
  WAREHOUSE_CONFIRM_WAREHOUSE_TRANSFER: 'TICKET_CONFIRM_WAREHOUSE_TRANSFER',
  WAREHOUSE_REJECT_WAREHOUSE_TRANSFER: 'TICKET_REJECT_WAREHOUSE_TRANSFER',
  WAREHOUSE_IMPORT_WAREHOUSE_TRANSFER: 'TICKET_IMPORT_WAREHOUSE_TRANSFER',
  WAREHOUSE_EXPORT_WAREHOUSE_TRANSFER: 'TICKET_EXPORT_WAREHOUSE_TRANSFER',
  TICKET_RETURN_WAREHOUSE_TRANSFER: 'TICKET_RETURN_WAREHOUSE_TRANSFER',
  TICKET_CANCEL_WAREHOUSE_TRANSFER: 'TICKET_CANCEL_WAREHOUSE_TRANSFER',
  WAREHOUSE_CONFIRM_EXPORT_WAREHOUSE_TRANSFER:
    'WAREHOUSE_CONFIRM_EXPORT_WAREHOUSE_TRANSFER',
  WAREHOUSE_RETURN_WAREHOUSE_TRANSFER: 'WAREHOUSE_RETURN_WAREHOUSE_TRANSFER',
  WAREHOUSE_CONFIRM_SYNC_WAREHOUSE_TRANSFER_TO_EBS:
    'WAREHOUSE_CONFIRM_SYNC_WAREHOUSE_TRANSFER_TO_EBS',
  WAREHOUSE_CANCEL_SYNC_WAREHOUSE_TRANSFER:
    'WAREHOUSE_CANCEL_SYNC_WAREHOUSE_TRANSFER',
  WAREHOUSE_CONFIRM_IMPORT_WAREHOUSE_TRANSFER:
    'WAREHOUSE_CONFIRM_IMPORT_WAREHOUSE_TRANSFER',
  WAREHOUSE_DETAIL_WAREHOUSE_TRANSFER_STATISTICS:
    'WAREHOUSE_DETAIL_WAREHOUSE_TRANSFER_STATISTICS',
  WAREHOUSE_LIST_WAREHOUSE_TRANSFER_STATISTICS:
    'WAREHOUSE_LIST_WAREHOUSE_TRANSFER_STATISTICS',

  WAREHOUSE_CREATE_WAREHOUSE_REPORT: 'WAREHOUSE_CREATE_WAREHOUSE_REPORT',
  WAREHOUSE_DELETE_WAREHOUSE_REPORT: 'WAREHOUSE_DELETE_WAREHOUSE_REPORT',
  WAREHOUSE_DETAIL_WAREHOUSE_REPORT: 'WAREHOUSE_DETAIL_WAREHOUSE_REPORT',
  WAREHOUSE_LIST_WAREHOUSE_REPORT: 'WAREHOUSE_LIST_WAREHOUSE_REPORT',
  WAREHOUSE_LIST_INVENTORY_STATISTICS: 'WAREHOUSE_LIST_INVENTORY_STATISTICS',
  WAREHOUSE_DETAIL_INVENTORY_STATISTICS:
    'WAREHOUSE_DETAIL_INVENTORY_STATISTICS',
  WAREHOUSE_LIST_WAREHOUSE_REPORT_STOCK:
    'WAREHOUSE_LIST_WAREHOUSE_REPORT_STOCK',
  ITEM_EXPORT_ITEM: 'ITEM_EXPORT_ITEM',
  CREATE_ITEM_WAREHOUSE_SOURCE_PERMISSION:
    'ITEM_CREATE_ITEM_WAREHOUSE_SOURCE_PERMISSION',
  UPDATE_ITEM_WAREHOUSE_SOURCE_PERMISSION:
    'ITEM_UPDATE_ITEM_WAREHOUSE_SOURCE_PERMISSION',
  WAREHOUSE_DETAIL_WAREHOUSE_SPACE: 'WAREHOUSE_DETAIL_WAREHOUSE_SPACE',
  WAREHOUSE_CREATE_WAREHOUSE_TYPE_SETTING:
    'WAREHOUSE_CREATE_WAREHOUSE_TYPE_SETTING',
  WAREHOUSE_UPDATE_WAREHOUSE_TYPE_SETTING:
    'WAREHOUSE_UPDATE_WAREHOUSE_TYPE_SETTING',
  WAREHOUSE_DELETE_WAREHOUSE_TYPE_SETTING:
    'WAREHOUSE_DELETE_WAREHOUSE_TYPE_SETTING',
  WAREHOUSE_DETAIL_WAREHOUSE_TYPE_SETTING:
    'WAREHOUSE_DETAIL_WAREHOUSE_TYPE_SETTING',
  WAREHOUSE_LIST_WAREHOUSE_TYPE_SETTING:
    'WAREHOUSE_LIST_WAREHOUSE_TYPE_SETTING',
  WAREHOUSE_IMPORT_WAREHOUSE_TYPE_SETTING:
    'WAREHOUSE_IMPORT_WAREHOUSE_TYPE_SETTING',
  WAREHOUSE_EXPORT_WAREHOUSE_TYPE_SETTING:
    'WAREHOUSE_EXPORT_WAREHOUSE_TYPE_SETTING',
  WAREHOUSE_CONFIRM_WAREHOUSE_TYPE_SETTING:
    'WAREHOUSE_CONFIRM_WAREHOUSE_TYPE_SETTING',
  WAREHOUSE_REJECT_WAREHOUSE_TYPE_SETTING:
    'WAREHOUSE_REJECT_WAREHOUSE_TYPE_SETTING',
  WAREHOUSE_LIST_INVENTORY_WARNING: 'WAREHOUSE_LIST_INVENTORY_WARNING',
  WAREHOUSE_CREATE_SUGGEST_ITEM_LOCATION:
    'WAREHOUSE_CREATE_SUGGEST_ITEM_LOCATION',
  WAREHOUSE_UPDATE_SUGGEST_ITEM_LOCATION:
    'WAREHOUSE_UPDATE_SUGGEST_ITEM_LOCATION',
  WAREHOUSE_DELETE_SUGGEST_ITEM_LOCATION:
    'WAREHOUSE_DELETE_SUGGEST_ITEM_LOCATION',
  WAREHOUSE_DETAIL_SUGGEST_ITEM_LOCATION:
    'WAREHOUSE_DETAIL_SUGGEST_ITEM_LOCATION',
  WAREHOUSE_LIST_SUGGEST_ITEM_LOCATION: 'WAREHOUSE_LIST_SUGGEST_ITEM_LOCATION',
  USER_SET_PERMISSION_USER: 'USER_SET_PERMISSION_USER',
  WAREHOUSE_DETAIL_BUSSINESS_TYPE: 'WAREHOUSE_DETAIL_BUSSINESS_TYPE',
  WAREHOUSE_LIST_BUSSINESS_TYPE: 'WAREHOUSE_LIST_BUSSINESS_TYPE',
  WAREHOUSE_CREATE_WAREHOUSE_EXPORT_PROPOSAL:
    'WAREHOUSE_CREATE_WAREHOUSE_EXPORT_PROPOSAL',
  WAREHOUSE_UPDATE_WAREHOUSE_EXPORT_PROPOSAL:
    'WAREHOUSE_UPDATE_WAREHOUSE_EXPORT_PROPOSAL',
  WAREHOUSE_DELETE_WAREHOUSE_EXPORT_PROPOSAL:
    'WAREHOUSE_DELETE_WAREHOUSE_EXPORT_PROPOSAL',
  WAREHOUSE_DETAIL_WAREHOUSE_EXPORT_PROPOSAL:
    'WAREHOUSE_DETAIL_WAREHOUSE_EXPORT_PROPOSAL',
  WAREHOUSE_LIST_WAREHOUSE_EXPORT_PROPOSAL:
    'WAREHOUSE_LIST_WAREHOUSE_EXPORT_PROPOSAL',
  WAREHOUSE_CONFIRM_WAREHOUSE_EXPORT_PROPOSAL:
    'WAREHOUSE_CONFIRM_WAREHOUSE_EXPORT_PROPOSAL',
  WAREHOUSE_REJECT_WAREHOUSE_EXPORT_PROPOSAL:
    'WAREHOUSE_REJECT_WAREHOUSE_EXPORT_PROPOSAL',
  WAREHOUSE_REQUEST_ITEM_CODE_WAREHOUSE_EXPORT_PROPOSAL:
    'WAREHOUSE_REQUEST_ITEM_CODE_WAREHOUSE_EXPORT_PROPOSAL',
  WAREHOUSE_QUICK_CREATE_WAREHOUSE_EXPORT_PROPOSAL:
    'WAREHOUSE_QUICK_CREATE_WAREHOUSE_EXPORT_PROPOSAL',
  WAREHOUSE_IMPORT_WAREHOUSE_EXPORT_PROPOSAL:
    'WAREHOUSE_IMPORT_WAREHOUSE_EXPORT_PROPOSAL',
  WAREHOUSE_EXPORT_WAREHOUSE_EXPORT_PROPOSAL:
    'WAREHOUSE_EXPORT_WAREHOUSE_EXPORT_PROPOSAL',
  WAREHOUSE_UPDATE_WAREHOUSE_EXPORT_AFTER_CONFIRM_PROPOSAL:
    'WAREHOUSE_UPDATE_WAREHOUSE_EXPORT_AFTER_CONFIRM_PROPOSAL',

  WAREHOUSE_CREATE_INVENTORY_SETTING: 'WAREHOUSE_CREATE_INVENTORY_SETTING',
  WAREHOUSE_UPDATE_INVENTORY_SETTING: 'WAREHOUSE_UPDATE_INVENTORY_SETTING',
  WAREHOUSE_DELETE_INVENTORY_SETTING: 'WAREHOUSE_DELETE_INVENTORY_SETTING',
  WAREHOUSE_DETAIL_INVENTORY_SETTING: 'WAREHOUSE_DETAIL_INVENTORY_SETTING',
  WAREHOUSE_LIST_INVENTORY_SETTING: 'WAREHOUSE_LIST_INVENTORY_SETTING',
  WAREHOUSE_IMPORT_INVENTORY_SETTING: 'WAREHOUSE_IMPORT_INVENTORY_SETTING',
  WAREHOUSE_EXPORT_INVENTORY_SETTING: 'WAREHOUSE_EXPORT_INVENTORY_SETTING',

  // inventory adjust
  WAREHOUSE_CREATE_INVENTORY_ADJUSTMENT:
    'WAREHOUSE_CREATE_INVENTORY_ADJUSTMENT',
  WAREHOUSE_UPDATE_INVENTORY_ADJUSTMENT:
    'WAREHOUSE_UPDATE_INVENTORY_ADJUSTMENT',
  WAREHOUSE_DELETE_INVENTORY_ADJUSTMENT:
    'WAREHOUSE_DELETE_INVENTORY_ADJUSTMENT',
  WAREHOUSE_DETAIL_INVENTORY_ADJUSTMENT:
    'WAREHOUSE_DETAIL_INVENTORY_ADJUSTMENT',
  WAREHOUSE_LIST_INVENTORY_ADJUSTMENT: 'WAREHOUSE_LIST_INVENTORY_ADJUSTMENT',
  WAREHOUSE_CONFIRM_INVENTORY_ADJUSTMENT:
    'WAREHOUSE_CONFIRM_INVENTORY_ADJUSTMENT',
  WAREHOUSE_REJECT_INVENTORY_ADJUSTMENT:
    'WAREHOUSE_REJECT_INVENTORY_ADJUSTMENT',
  WAREHOUSE_IMPORT_INVENTORY_ADJUSTMENT:
    'WAREHOUSE_IMPORT_INVENTORY_ADJUSTMENT',
  WAREHOUSE_EXPORT_INVENTORY_ADJUSTMENT:
    'WAREHOUSE_EXPORT_INVENTORY_ADJUSTMENT',

  WAREHOUSE_SEARCH_INVENTORY_MANAGEMENT:
    'WAREHOUSE_SEARCH_INVENTORY_MANAGEMENT',
  WAREHOUSE_CLASSIFY_INVENTORY_MANAGEMENT:
    'WAREHOUSE_CLASSIFY_INVENTORY_MANAGEMENT',
  WAREHOUSE_STATISTICAL_OF_OVERDUE_STORAGE_INVENTORY_MANAGEMENT:
    'WAREHOUSE_STATISTICAL_OF_OVERDUE_STORAGE_INVENTORY_MANAGEMENT',
  WAREHOUSE_STATISTIC_IMPORT_WAREHOUSE_TRANSACTION:
    'WAREHOUSE_STATISTIC_IMPORT_WAREHOUSE_TRANSACTION',
  WAREHOUSE_STATISTIC_EXPORT_WAREHOUSE_TRANSACTION:
    'WAREHOUSE_STATISTIC_EXPORT_WAREHOUSE_TRANSACTION',
  WAREHOUSE_STATISTIC_REPORT: 'WAREHOUSE_STATISTIC_REPORT',

  // reason-management
  SALE_LIST_REASON: 'MASTER_DATA_LIST_REASON',
  SALE_CREATE_REASON: 'MASTER_DATA_CREATE_REASON',
  SALE_UPDATE_REASON: 'MASTER_DATA_UPDATE_REASON',
  SALE_DETAIL_REASON: 'MASTER_DATA_DETAIL_REASON',
  SALE_IMPORT_REASON: 'MASTER_DATA_IMPORT_REASON',
  SALE_EXPORT_REASON: 'MASTER_DATA_EXPORT_REASON',
  SALE_INACTIVE_REASON: 'MASTER_DATA_INACTIVE_REASON',
  SALE_ACTIVE_REASON: 'MASTER_DATA_ACTIVE_REASON',
  SALE_DELETE_REASON: 'MASTER_DATA_DELETE_REASON',

  WAREHOUSE_CREATE_BUSSINESS_TYPE: 'WAREHOUSE_CREATE_BUSSINESS_TYPE',
  WAREHOUSE_UPDATE_BUSSINESS_TYPE: 'WAREHOUSE_UPDATE_BUSSINESS_TYPE',
  WAREHOUSE_REJECT_BUSSINESS_TYPE: 'WAREHOUSE_REJECT_BUSSINESS_TYPE',
  WAREHOUSE_CONFIRM_BUSSINESS_TYPE: 'WAREHOUSE_CONFIRM_BUSSINESS_TYPE',
  ITEM_UPDATE_OBJECT_CATEGORY: 'ITEM_UPDATE_OBJECT_CATEGORY',
  ITEM_REJECT_OBJECT_CATEGORY: 'ITEM_REJECT_OBJECT_CATEGORY',
  ITEM_CONFIRM_OBJECT_CATEGORY: 'ITEM_CONFIRM_OBJECT_CATEGORY',
  ITEM_LIST_ITEM_QUALITY: 'ITEM_LIST_ITEM_QUALITY',
  ITEM_CREATE_ITEM_QUALITY: 'ITEM_CREATE_ITEM_QUALITY',
  ITEM_UPDATE_ITEM_QUALITY: 'ITEM_UPDATE_ITEM_QUALITY',
  ITEM_DETAIL_ITEM_QUALITY: 'ITEM_DETAIL_ITEM_QUALITY',
  ITEM_IMPORT_ITEM_QUALITY: 'ITEM_IMPORT_ITEM_QUALITY',
  ITEM_EXPORT_ITEM_QUALITY: 'ITEM_EXPORT_ITEM_QUALITY',
  ITEM_REJECT_ITEM_QUALITY: 'ITEM_REJECT_ITEM_QUALITY',
  ITEM_CONFIRM_ITEM_QUALITY: 'ITEM_CONFIRM_ITEM_QUALITY',

  ITEM_CREATE_MANUFACTURING_COUNTRY: 'ITEM_CREATE_MANUFACTURING_COUNTRY',
  ITEM_UPDATE_MANUFACTURING_COUNTRY: 'ITEM_UPDATE_MANUFACTURING_COUNTRY',
  ITEM_DELETE_MANUFACTURING_COUNTRY: 'ITEM_DELETE_MANUFACTURING_COUNTRY',
  ITEM_REJECT_MANUFACTURING_COUNTRY: 'ITEM_REJECT_MANUFACTURING_COUNTRY',
  ITEM_CONFIRM_MANUFACTURING_COUNTRY: 'ITEM_CONFIRM_MANUFACTURING_COUNTRY',
  ITEM_DETAIL_MANUFACTURING_COUNTRY: 'ITEM_DETAIL_MANUFACTURING_COUNTRY',
  ITEM_LIST_MANUFACTURING_COUNTRY: 'ITEM_LIST_MANUFACTURING_COUNTRY',

  SALE_LIST_COST_TYPE: 'SALE_LIST_COST_TYPE',
  SALE_CREATE_COST_TYPE: 'SALE_CREATE_COST_TYPE',
  SALE_UPDATE_COST_TYPE: 'SALE_UPDATE_COST_TYPE',
  SALE_DETAIL_COST_TYPE: 'SALE_DETAIL_COST_TYPE',
  SALE_REJECT_COST_TYPE: 'SALE_REJECT_COST_TYPE',
  SALE_CONFIRM_COST_TYPE: 'SALE_CONFIRM_COST_TYPE',
  DATASYNC_LIST_JOB: 'DATASYNC_LIST_JOB',
  DATASYNC_RETRY_JOB: 'DATASYNC_RETRY_JOB',
  DATASYNC_CANCEL_JOB: 'DATASYNC_CANCEL_JOB',
  SALE_LIST_SOURCE: 'SALE_LIST_SOURCE',
  CREATE_SOURCE: 'SALE_CREATE_SOURCE',
  UPDATE_SOURCE: 'SALE_UPDATE_SOURCE',
  DETAIL_SOURCE: 'SALE_DETAIL_SOURCE',
  IMPORT_SOURCE: 'SALE_IMPORT_SOURCE',
  EXPORT_SOURCE: 'SALE_EXPORT_SOURCE',
  REJECT_SOURCE: 'SALE_REJECT_SOURCE',
  CONFIRM_SOURCE: 'SALE_CONFIRM_SOURCE',
  WAREHOUSE_LIST_LOCATION: 'WAREHOUSE_LIST_LOCATION',
  WAREHOUSE_CREATE_LOCATION: 'WAREHOUSE_CREATE_LOCATION',
  WAREHOUSE_DELETE_LOCATION: 'WAREHOUSE_DELETE_LOCATION',
  WAREHOUSE_UPDATE_LOCATION: 'WAREHOUSE_UPDATE_LOCATION',
  WAREHOUSE_DETAIL_LOCATION: 'WAREHOUSE_DETAIL_LOCATION',
  WAREHOUSE_REJECT_LOCATION: 'WAREHOUSE_REJECT_LOCATION',
  WAREHOUSE_CONFIRM_LOCATION: 'WAREHOUSE_CONFIRM_LOCATION',
  WAREHOUSE_IMPORT_LOCATION: 'WAREHOUSE_IMPORT_LOCATION',
  WAREHOUSE_EXPORT_LOCATION: 'WAREHOUSE_EXPORT_LOCATION',
  WAREHOUSE_CREATE_PICK_UP_AREA: 'WAREHOUSE_CREATE_PICK_UP_AREA',
  WAREHOUSE_UPDATE_PICK_UP_AREA: 'WAREHOUSE_UPDATE_PICK_UP_AREA',
  WAREHOUSE_DELETE_PICK_UP_AREA: 'WAREHOUSE_DELETE_PICK_UP_AREA',
  WAREHOUSE_DETAIL_PICK_UP_AREA: 'WAREHOUSE_DETAIL_PICK_UP_AREA',
  WAREHOUSE_LIST_PICK_UP_AREA: 'WAREHOUSE_LIST_PICK_UP_AREA',
  WAREHOUSE_CONFIRM_PICK_UP_AREA: 'WAREHOUSE_CONFIRM_PICK_UP_AREA',
  WAREHOUSE_REJECT_PICK_UP_AREA: 'WAREHOUSE_REJECT_PICK_UP_AREA',
  EXPORT_PICK_UP_AREA: 'EXPORT_PICK_UP_AREA',
  IMPORT_PICK_UP_AREA: 'IMPORT_PICK_UP_AREA',
  WAREHOUSE_CREATE_PICK_UP_AREA_DISTANCE:
    'WAREHOUSE_CREATE_PICK_UP_AREA_DISTANCE',
  WAREHOUSE_UPDATE_PICK_UP_AREA_DISTANCE:
    'WAREHOUSE_UPDATE_PICK_UP_AREA_DISTANCE',
  WAREHOUSE_DELETE_PICK_UP_AREA_DISTANCE:
    'WAREHOUSE_DELETE_PICK_UP_AREA_DISTANCE',
  WAREHOUSE_DETAIL_PICK_UP_AREA_DISTANCE:
    'WAREHOUSE_DETAIL_PICK_UP_AREA_DISTANCE',
  WAREHOUSE_LIST_PICK_UP_AREA_DISTANCE: 'WAREHOUSE_LIST_PICK_UP_AREA_DISTANCE',
  WAREHOUSE_CONFIRM_PICK_UP_AREA_DISTANCE:
    'WAREHOUSE_CONFIRM_PICK_UP_AREA_DISTANCE',
  WAREHOUSE_REJECT_PICK_UP_AREA_DISTANCE:
    'WAREHOUSE_REJECT_PICK_UP_AREA_DISTANCE',
  EXPORT_PICK_UP_AREA_DISTANCE: 'EXPORT_PICK_UP_AREA_DISTANCE',
  IMPORT_PICK_UP_AREA_DISTANCE: 'IMPORT_PICK_UP_AREA_DISTANCE',
  WAREHOUSE_CREATE_PICK_UP_TIME: 'WAREHOUSE_CREATE_PICK_UP_TIME',
  WAREHOUSE_UPDATE_PICK_UP_TIME: 'WAREHOUSE_UPDATE_PICK_UP_TIME',
  WAREHOUSE_DELETE_PICK_UP_TIME: 'WAREHOUSE_DELETE_PICK_UP_TIME',
  WAREHOUSE_DETAIL_PICK_UP_TIME: 'WAREHOUSE_DETAIL_PICK_UP_TIME',
  WAREHOUSE_LIST_PICK_UP_TIME: 'WAREHOUSE_LIST_PICK_UP_TIME',
  WAREHOUSE_CONFIRM_PICK_UP_TIME: 'ACTIVE_PICK_UP_TIME',
  WAREHOUSE_REJECT_PICK_UP_TIME: 'INACTIVE_PICK_UP_TIME',
  EXPORT_PICK_UP_TIME: 'EXPORT_PICK_UP_TIME',
  IMPORT_PICK_UP_TIME: 'IMPORT_PICK_UP_TIME',
  INACTIVE_PICK_UP_TIME: 'INACTIVE_PICK_UP_TIME',
  ACTIVE_PICK_UP_TIME: 'ACTIVE_PICK_UP_TIME',
  SALE_LIST_ORGANIZATION_PAYMENT: 'SALE_LIST_ORGANIZATION_PAYMENT',
  SALE_CREATE_ORGANIZATION_PAYMENT: 'SALE_CREATE_ORGANIZATION_PAYMENT',
  SALE_UPDATE_ORGANIZATION_PAYMENT: 'SALE_UPDATE_ORGANIZATION_PAYMENT',
  SALE_REJECT_ORGANIZATION_PAYMENT: 'SALE_REJECT_ORGANIZATION_PAYMENT',
  SALE_CONFIRM_ORGANIZATION_PAYMENT: 'SALE_CONFIRM_ORGANIZATION_PAYMENT',
  SALE_DETAIL_ORGANIZATION_PAYMENT: 'SALE_DETAIL_ORGANIZATION_PAYMENT',
  SALE_IMPORT_ORGANIZATION_PAYMENT: 'SALE_IMPORT_ORGANIZATION_PAYMENT',
  SALE_EXPORT_ORGANIZATION_PAYMENT: 'SALE_EXPORT_ORGANIZATION_PAYMENT',
  WAREHOUSE_LIST_LOCATOR: 'WAREHOUSE_LIST_LOCATOR',
  WAREHOUSE_CREATE_LOCATOR: 'WAREHOUSE_CREATE_LOCATOR',
  WAREHOUSE_UPDATE_LOCATOR: 'WAREHOUSE_UPDATE_LOCATOR',
  WAREHOUSE_DELETE_LOCATOR: 'WAREHOUSE_DELETE_LOCATOR',
  WAREHOUSE_REJECT_LOCATOR: 'WAREHOUSE_REJECT_LOCATOR',
  WAREHOUSE_CONFIRM_LOCATOR: 'WAREHOUSE_CONFIRM_LOCATOR',
  WAREHOUSE_DETAIL_LOCATOR: 'WAREHOUSE_DETAIL_LOCATOR',
  WAREHOUSE_IMPORT_LOCATOR: 'WAREHOUSE_IMPORT_LOCATOR',
  WAREHOUSE_EXPORT_LOCATOR: 'WAREHOUSE_EXPORT_LOCATOR',
  EXPORT_LOCATOR: 'EXPORT_LOCATOR',
  WAREHOUSE_LIST_INVENTORY_TIME_LIMIT: 'WAREHOUSE_LIST_INVENTORY_TIME_LIMIT',
  WAREHOUSE_CREATE_INVENTORY_TIME_LIMIT:
    'WAREHOUSE_CREATE_INVENTORY_TIME_LIMIT',
  WAREHOUSE_UPDATE_INVENTORY_TIME_LIMIT:
    'WAREHOUSE_UPDATE_INVENTORY_TIME_LIMIT',
  WAREHOUSE_DELETE_INVENTORY_TIME_LIMIT:
    'WAREHOUSE_DELETE_INVENTORY_TIME_LIMIT',
  WAREHOUSE_DETAIL_INVENTORY_TIME_LIMIT:
    'WAREHOUSE_DETAIL_INVENTORY_TIME_LIMIT',
  // ITEM_LIST_INVENTORY_QUANTITY_NORM: 'ITEM_LIST_INVENTORY_QUANTITY_NORM',
  // ITEM_CREATE_INVENTORY_QUANTITY_NORM: 'ITEM_CREATE_INVENTORY_QUANTITY_NORM',
  // ITEM_UPDATE_INVENTORY_QUANTITY_NORM: 'ITEM_UPDATE_INVENTORY_QUANTITY_NORM',
  // ITEM_DELETE_INVENTORY_QUANTITY_NORM: 'ITEM_DELETE_INVENTORY_QUANTITY_NORM',
  // ITEM_DETAIL_INVENTORY_QUANTITY_NORM: 'ITEM_DETAIL_INVENTORY_QUANTITY_NORM',
  // ITEM_IMPORT_INVENTORY_QUANTITY_NORM: 'ITEM_IMPORT_INVENTORY_QUANTITY_NORM',
  // ITEM_EXPORT_INVENTORY_QUANTITY_NORM: 'ITEM_EXPORT_INVENTORY_QUANTITY_NORM',
  ITEM_IMPORT_INVENTORY_SETTING: 'ITEM_IMPORT_INVENTORY_SETTING',
  ITEM_EXPORT_INVENTORY_SETTING: 'ITEM_EXPORT_INVENTORY_SETTING',
  USER_CREATE_USER_ROLE_SETTING: 'USER_CREATE_USER_ROLE_SETTING',
  USER_UPDATE_USER_ROLE_SETTING: 'USER_UPDATE_USER_ROLE_SETTING',
  USER_LOCK_USER_ROLE_SETTING: 'USER_LOCK_USER_ROLE_SETTING',
  USER_UNLOCK_USER_ROLE_SETTING: 'USER_UNLOCK_USER_ROLE_SETTING',
  USER_DELETE_USER_ROLE_SETTING: 'USER_DELETE_USER_ROLE_SETTING',
  USER_DETAIL_USER_ROLE_SETTING: 'USER_DETAIL_USER_ROLE_SETTING',
  USER_LIST_USER_ROLE_SETTING: 'USER_LIST_USER_ROLE_SETTING',
  REPORT_CONFIG_QR: 'REPORT_CONFIG_QR',
  REPORT_CREATE_QR_CODE_SETTING: 'REPORT_CREATE_QR_CODE_SETTING',
  REPORT_GET_QR_CODE_SETTING: 'REPORT_GET_QR_CODE_SETTING',
  REPORT_LIST_CONFIG_SIGNATURE: 'REPORT_LIST_CONFIG_SIGNATURE',
  REPORT_CREATE_CONFIG_SIGNATURE: 'REPORT_CREATE_CONFIG_SIGNATURE',
  CREATE_SALE_ORDER: 'SALE_CREATE_SALE_ORDER',
  UPDATE_SALE_ORDER: 'SALE_UPDATE_SALE_ORDER',
  DELETE_SALE_ORDER: 'SALE_DELETE_SALE_ORDER',
  DETAIL_SALE_ORDER: 'SALE_DETAIL_SALE_ORDER',
  LIST_SALE_ORDER: 'SALE_LIST_SALE_ORDER',
  CONFIRM_SALE_ORDER: 'SALE_CONFIRM_SALE_ORDER',
  COMPLETE_SALE_ORDER: 'SALE_COMPLETE_SALE_ORDER',
  APPROVE_SALE_ORDER: 'SALE_APPROVE_SALE_ORDER',
  REJECT_SALE_ORDER: 'SALE_REJECT_SALE_ORDER',
  EXPORT_SALE_ORDER: 'SALE_EXPORT_SALE_ORDER',
  // ERROR_TYPE_GROUP
  CREATE_ERROR_TYPE: 'MMS_CREATE_ERROR_TYPE',
  LIST_ERROR_TYPE: 'MMS_LIST_ERROR_TYPE',
  DETAIL_ERROR_TYPE: 'MMS_DETAIL_ERROR_TYPE',
  UPDATE_ERROR_TYPE: 'MMS_UPDATE_ERROR_TYPE',
  UPDATE_STATUS_ERROR_TYPE: 'MMS_UPDATE_STATUS_ERROR_TYPE',
  DELETE_ERROR_TYPE: 'MMS_DELETE_ERROR_TYPE',
  IMPORT_ERROR_TYPE: 'MMS_IMPORT_ERROR_TYPE',
  EXPORT_ERROR_TYPE: 'MMS_EXPORT_ERROR_TYPE',

  //production-line
  CREATE_PRODUCTION_LINE: 'PRODUCE_CREATE_PRODUCTION_LINE',
  UPDATE_PRODUCTION_LINE: 'PRODUCE_UPDATE_PRODUCTION_LINE',
  DELETE_PRODUCTION_LINE: 'PRODUCE_DELETE_PRODUCTION_LINE',
  DETAIL_PRODUCTION_LINE: 'PRODUCE_DETAIL_PRODUCTION_LINE',
  LIST_PRODUCTION_LINE: 'PRODUCE_LIST_PRODUCTION_LINE',
  INACTIVE_PRODUCTION_LINE: 'PRODUCE_INACTIVE_PRODUCTION_LINE',
  ACTIVE_PRODUCTION_LINE: 'PRODUCE_ACTIVE_PRODUCTION_LINE',
  IMPORT_PRODUCTION_LINE: 'PRODUCE_IMPORT_PRODUCTION_LINE',
  EXPORT_PRODUCTION_LINE: 'PRODUCE_EXPORT_PRODUCTION_LINE',

  // define-packing
  CREATE_PACKING: 'PACKING_CREATE_PACKING',
  UPDATE_PACKING: 'PACKING_UPDATE_PACKING',
  DELETE_PACKING: 'PACKING_DELETE_PACKING',
  DETAIL_PACKING: 'PACKING_DETAIL_PACKING',
  LIST_PACKING: 'PACKING_LIST_PACKING',
  IMPORT_PACKING: 'PACKING_IMPORT_PACKING',
  EXPORT_PACKING: 'PACKING_EXPORT_PACKING',

  // plant-management
  CREATE_PLANT: 'PRODUCE_CREATE_PLANT',
  UPDATE_PLANT: 'PRODUCE_UPDATE_PLANT',
  DETAIL_PLANT: 'PRODUCE_DETAIL_PLANT',
  DELETE_PLANT: 'PRODUCE_DELETE_PLANT',
  LIST_PLANT: 'PRODUCE_LIST_PLANT',
  ACTIVE_PLANT: 'PRODUCE_ACTIVE_PLANT',
  INACTIVE_PLANT: 'PRODUCE_INACTIVE_PLANT',
  IMPORT_PLANT: 'PRODUCE_IMPORT_PLANT',
  EXPORT_PLANT: 'PRODUCE_EXPORT_PLANT',

  // routing
  CREATE_ROUTING: 'PRODUCE_CREATE_ROUTING',
  UPDATE_ROUTING: 'PRODUCE_UPDATE_ROUTING',
  DETAIL_ROUTING: 'PRODUCE_DETAIL_ROUTING',
  DELETE_ROUTING: 'PRODUCE_DELETE_ROUTING',
  LIST_ROUTING: 'PRODUCE_LIST_ROUTING',
  ACTIVE_ROUTING: 'PRODUCE_ACTIVE_ROUTING',
  INACTIVE_ROUTING: 'PRODUCE_INACTIVE_ROUTING',
  IMPORT_ROUTING: 'PRODUCE_IMPORT_ROUTING',
  EXPORT_ROUTING: 'PRODUCE_EXPORT_ROUTING',

  // producing-step
  CREATE_PRODUCING_STEP: 'PRODUCE_CREATE_PRODUCING_STEP',
  UPDATE_PRODUCING_STEP: 'PRODUCE_UPDATE_PRODUCING_STEP',
  DETAIL_PRODUCING_STEP: 'PRODUCE_DETAIL_PRODUCING_STEP',
  LIST_PRODUCING_STEP: 'PRODUCE_LIST_PRODUCING_STEP',
  DELETE_PRODUCING_STEP: 'PRODUCE_DELETE_PRODUCING_STEP',
  ACTIVE_PRODUCING_STEP: 'PRODUCE_ACTIVE_PRODUCING_STEP',
  INACTIVE_PRODUCING_STEP: 'PRODUCE_INACTIVE_PRODUCING_STEP',
  IMPORT_PRODUCING_STEP: 'PRODUCE_IMPORT_PRODUCING_STEP',
  EXPORT_PRODUCING_STEP: 'PRODUCE_EXPORT_PRODUCING_STEP',

  // manufacturing-order
  CREATE_MANUFACTURING_ORDER: 'PRODUCE_CREATE_MANUFACTURING_ORDER',
  UPDATE_MANUFACTURING_ORDER: 'PRODUCE_UPDATE_MANUFACTURING_ORDER',
  DETAIL_MANUFACTURING_ORDER: 'PRODUCE_DETAIL_MANUFACTURING_ORDER',
  DELETE_MANUFACTURING_ORDER: 'PRODUCE_DELETE_MANUFACTURING_ORDER',
  LIST_MANUFACTURING_ORDER: 'PRODUCE_LIST_MANUFACTURING_ORDER',
  REJECT_MANUFACTURING_ORDER: 'PRODUCE_REJECT_MANUFACTURING_ORDER',
  CONFIRM_MANUFACTURING_ORDER: 'PRODUCE_CONFIRM_MANUFACTURING_ORDER',
  SUBMIT_PENDING_MANUFACTURING_ORDER:
    'PRODUCE_SUBMIT_PENDING_MANUFACTURING_ORDER',
  IMPORT_MANUFACTURING_ORDER: 'PRODUCE_IMPORT_MANUFACTURING_ORDER',
  EXPORT_MANUFACTURING_ORDER: 'PRODUCE_EXPORT_MANUFACTURING_ORDER',
  // item line
  ITEM_CREATE_ITEM_LINE: 'ITEM_CREATE_ITEM_LINE',
  ITEM_UPDATE_ITEM_LINE: 'ITEM_UPDATE_ITEM_LINE',
  ITEM_DETAIL_ITEM_LINE: 'ITEM_DETAIL_ITEM_LINE',
  ITEM_DELETE_ITEM_LINE: 'ITEM_DELETE_ITEM_LINE',
  ITEM_LIST_ITEM_LINE: 'ITEM_LIST_ITEM_LINE',
  ITEM_ACTIVE_ITEM_LINE: 'ITEM_ACTIVE_ITEM_LINE',
  ITEM_INACTIVE_ITEM_LINE: 'ITEM_INACTIVE_ITEM_LINE',
  ITEM_IMPORT_ITEM_LINE: 'ITEM_IMPORT_ITEM_LINE',
  ITEM_EXPORT_ITEM_LINE: 'ITEM_EXPORT_ITEM_LINE',

  // export plan
  SALE_ORDER_INSTRUCTION_CREATE_EXPORT_PLAN:
    'SALE_ORDER_INSTRUCTION_CREATE_EXPORT_PLAN',
  SALE_ORDER_INSTRUCTION_UPDATE_EXPORT_PLAN:
    'SALE_ORDER_INSTRUCTION_UPDATE_EXPORT_PLAN',
  SALE_ORDER_INSTRUCTION_DETAIL_EXPORT_PLAN:
    'SALE_ORDER_INSTRUCTION_DETAIL_EXPORT_PLAN',
  SALE_ORDER_INSTRUCTION_DELETE_EXPORT_PLAN:
    'SALE_ORDER_INSTRUCTION_DELETE_EXPORT_PLAN',
  SALE_ORDER_INSTRUCTION_LIST_EXPORT_PLAN:
    'SALE_ORDER_INSTRUCTION_LIST_EXPORT_PLAN',
  SALE_ORDER_INSTRUCTION_SUBMIT_EXPORT_PLAN:
    'SALE_ORDER_INSTRUCTION_SUBMIT_EXPORT_PLAN',
  SALE_ORDER_INSTRUCTION_APPROVE_EXPORT_PLAN:
    'SALE_ORDER_INSTRUCTION_APPROVE_EXPORT_PLAN',
  SALE_ORDER_INSTRUCTION_REJECT_EXPORT_PLAN:
    'SALE_ORDER_INSTRUCTION_REJECT_EXPORT_PLAN',
  SALE_ORDER_INSTRUCTION_CANCEL_EXPORT_PLAN:
    'SALE_ORDER_INSTRUCTION_CANCEL_EXPORT_PLAN',
  SALE_ORDER_INSTRUCTION_EXPORT_PLAN: 'SALE_ORDER_INSTRUCTION_EXPORT_PLAN',

  // error code
  PRODUCE_CREATE_ERROR_CODE: 'MASTER_DATA_CREATE_ERROR_CODE',
  PRODUCE_UPDATE_ERROR_CODE: 'MASTER_DATA_UPDATE_ERROR_CODE',
  PRODUCE_GET_DETAIL_ERROR_CODE: 'MASTER_DATA_DETAIL_ERROR_CODE',
  PRODUCE_DELETE_ERROR_CODE: 'MASTER_DATA_DELETE_ERROR_CODE',
  PRODUCE_GET_LIST_ERROR_CODE: 'MASTER_DATA_LIST_ERROR_CODE',
  PRODUCE_ACTIVE_ERROR_CODE: 'MASTER_DATA_ACTIVE_ERROR_CODE',
  PRODUCE_INACTIVE_ERROR_CODE: 'MASTER_DATA_INACTIVE_ERROR_CODE',
  PRODUCE_IMPORT_ERROR_CODE: 'MASTER_DATA_IMPORT_ERROR_CODE',
  PRODUCE_EXPORT_ERROR_CODE: 'MASTER_DATA_EXPORT_ERROR_CODE',
  REPORT_DOWNLOAD_FILE: 'MMS_REPORT_DOWNLOAD_FILE_MENU',

  // item-norm
  CREATE_BOM: 'MMS_CREATE_BOM',
  CLONE_BOM_VERSION: 'PRODUCE_CLONE_VERSION_BOM',
  ACTIVE_BOM_VERSION: 'PRODUCE_ACTIVE_VERSION_BOM',
  DELETE_BOM_VERSION: 'PRODUCE_DELETE_VERSION_BOM',
  BOM_GROUP: 'MMS_BOM_GROUP',
  LIST_BOM: 'MMS_GET_LIST_BOM_VERSIONS',
  UPDATE_BOM_VERSION: 'MMS_UPDATE_BOM_VERSIONS',
  CONFIRM_BOM_VERSION: 'PRODUCE_CONFIRM_VERSION_BOM',
  REJECT_BOM_VERSION: 'PRODUCE_REJECT_VERSION_BOM',
  SUBMIT_PENDING_BOM_VERSION: 'PRODUCE_SUBMIT_PENDING_VERSION_BOM',
  DETAIL_BOM: 'MMS_GET_DETAIL_BOM_VERSIONS',
  EXPORT_BOM: 'MMS_IMPORT_BOM',
  IMPORT_BOM: 'MMS_EXPORT_BOM',
  // EXPORT_BOM_VERSION: 'PRODUCE_EXPORT_BOM_VERSION',

  // bom-import-export
  CREATE_BOM_IMPORT_EXPORT: 'PRODUCE_CREATE_BOM_IMPORT_EXPORT',
  CLONE_BOM_IMPORT_EXPORT_VERSION: 'PRODUCE_CLONE_VERSION_BOM_IMPORT_EXPORT',
  ACTIVE_BOM_IMPORT_EXPORT_VERSION: 'PRODUCE_ACTIVE_VERSION_BOM_IMPORT_EXPORT',
  DELETE_BOM_IMPORT_EXPORT_VERSION: 'PRODUCE_DELETE_VERSION_BOM_IMPORT_EXPORT',
  LIST_BOM_IMPORT_EXPORT: 'PRODUCE_LIST_BOM_IMPORT_EXPORT',
  UPDATE_BOM_IMPORT_EXPORT_VERSION: 'PRODUCE_UPDATE_VERSION_BOM_IMPORT_EXPORT',
  CONFIRM_BOM_IMPORT_EXPORT_VERSION:
    'PRODUCE_CONFIRM_VERSION_BOM_IMPORT_EXPORT',
  REJECT_BOM_IMPORT_EXPORT_VERSION: 'PRODUCE_REJECT_VERSION_BOM_IMPORT_EXPORT',
  SUBMIT_PENDING_BOM_IMPORT_EXPORT_VERSION:
    'PRODUCE_SUBMIT_PENDING_VERSION_BOM_IMPORT_EXPORT',
  DETAIL_BOM_IMPORT_EXPORT: 'PRODUCE_DETAIL_BOM_IMPORT_EXPORT',
  EXPORT_BOM_IMPORT_EXPORT: 'PRODUCE_EXPORT_BOM_IMPORT_EXPORT',
  EXPORT_BOM_VERSION_IMPORT_EXPORT: 'PRODUCE_EXPORT_BOM_VERSION_IMPORT_EXPORT',

  // productivity device
  MMS_CREATE_DEVICE_PERFORMANCE: 'MMS_CREATE_DEVICE_PERFORMANCE',
  MMS_UPDATE_DEVICE_PERFORMANCE: 'MMS_UPDATE_DEVICE_PERFORMANCE',
  MMS_DETAIL_DEVICE_PERFORMANCE: 'MMS_DETAIL_DEVICE_PERFORMANCE',
  MMS_DELETE_DEVICE_PERFORMANCE: 'MMS_DELETE_DEVICE_PERFORMANCE',
  MMS_LIST_DEVICE_PERFORMANCE: 'MMS_LIST_DEVICE_PERFORMANCE',
  MMS_ACTIVE_DEVICE_PERFORMANCE: 'MMS_ACTIVE_DEVICE_PERFORMANCE',
  MMS_INACTIVE_DEVICE_PERFORMANCE: 'MMS_INACTIVE_DEVICE_PERFORMANCE',
  MMS_IMPORT_DEVICE_PERFORMANCE: 'MMS_IMPORT_DEVICE_PERFORMANCE',
  MMS_EXPORT_DEVICE_PERFORMANCE: 'MMS_EXPORT_DEVICE_PERFORMANCE',

  // inventory-calendar
  // TICKET_STOCKTAKING_COMMAND_LIST: 'TICKET_STOCKTAKING_COMMAND_LIST',
  // TICKET_STOCKTAKING_COMMAND_CREATE: 'TICKET_STOCKTAKING_COMMAND_CREATE',
  // TICKET_STOCKTAKING_COMMAND_UPDATE: 'TICKET_STOCKTAKING_COMMAND_UPDATE',
  // TICKET_STOCKTAKING_COMMAND_DELETE: 'TICKET_STOCKTAKING_COMMAND_DELETE',
  // TICKET_STOCKTAKING_COMMAND_APPROVE: 'TICKET_STOCKTAKING_COMMAND_APPROVE',
  // TICKET_STOCKTAKING_COMMAND_REJECT: 'TICKET_STOCKTAKING_COMMAND_REJECT',
  // TICKET_STOCKTAKING_COMMAND_FINISH: 'TICKET_STOCKTAKING_COMMAND_FINISH',
  // TICKET_STOCKTAKING_PLAN_TICKET_LIST: 'TICKET_STOCKTAKING_PLAN_TICKET_LIST',
  // TICKET_STOCKTAKING_PLAN_DETAIL: 'TICKET_STOCKTAKING_PLAN_DETAIL',
  // TICKET_STOCKTAKING_PLAN_CREATE: 'TICKET_STOCKTAKING_PLAN_CREATE',
  // TICKET_STOCKTAKING_PLAN_APPROVE: 'TICKET_STOCKTAKING_PLAN_APPROVE',
  // TICKET_STOCKTAKING_PLAN_REJECT: 'TICKET_STOCKTAKING_PLAN_REJECT',
  // TICKET_STOCKTAKING_PLAN_DELETE: 'TICKET_STOCKTAKING_PLAN_DELETE',
  // TICKET_STOCKTAKING_EXECUTE: 'TICKET_STOCKTAKING_EXECUTE',
  // TICKET_STOCKTAKING_TICKET_CONFIRM_FINISH:
  //   'TICKET_STOCKTAKING_TICKET_CONFIRM_FINISH',
  // TICKET_STOCKTAKING_TICKET_APPROVE: 'TICKET_STOCKTAKING_TICKET_APPROVE',
  // TICKET_STOCKTAKING_TICKET_REJECT: 'TICKET_STOCKTAKING_TICKET_REJECT',
  // TICKET_STOCKTAKING_TICKET_CONFIRM_STOP:
  //   'TICKET_STOCKTAKING_TICKET_CONFIRM_STOP',
  // TICKET_STOCKTAKING_TICKET_DETAIL: 'TICKET_STOCKTAKING_TICKET_DETAIL',
  // TICKET_STOCKTAKING_TICKET_PRINT_DOWNLOAD:
  //   'TICKET_STOCKTAKING_TICKET_PRINT_DOWNLOAD',
  // TICKET_STOCKTAKING_RESULT_EXPORT: 'TICKET_STOCKTAKING_RESULT_EXPORT',
  // TICKET_STOCKTAKING_PERIODIC_TYPE: 'TICKET_STOCKTAKING_PERIODIC_TYPE',
  // TICKET_STOCKTAKING_SUDDEN_TYPE: 'TICKET_STOCKTAKING_SUDDEN_TYPE',
  // TICKET_STOCKTAKING_LOGIC_WAREHOUSE_METHOD:
  //   'TICKET_STOCKTAKING_LOGIC_WAREHOUSE_METHOD',
  // TICKET_STOCKTAKING_FIELD_WAREHOUSE_METHOD:
  //   'TICKET_STOCKTAKING_FIELD_WAREHOUSE_METHOD',

  // shipping-instruction
  LIST_SHIPPING_INSTRUCTION: 'SALE_ORDER_INSTRUCTION_LIST_EXPORT_DIRECTIVE',
  DETAIL_SHIPPING_INSTRUCTION: 'SALE_ORDER_INSTRUCTION_DETAIL_EXPORT_DIRECTIVE',
  EXPORT_SHIPPING_INSTRUCTION: 'SALE_ORDER_INSTRUCTION_EXPORT_DIRECTIVE_LIST',

  // customer-management
  CREATE_CUSTOMER: 'SALE_CREATE_CUSTOMER',
  UPDATE_CUSTOMER: 'SALE_UPDATE_CUSTOMER',
  LIST_CUSTOMER: 'SALE_LIST_CUSTOMER',
  DETAIL_CUSTOMER: 'SALE_DETAIL_CUSTOMER',
  CHANGE_STATUS_CUSTOMER: 'SALE_CHANGE_STATUS_CUSTOMER',
  EXPORT_CUSTOMER: 'SALE_EXPORT_CUSTOMER',
  IMPORT_CUSTOMER: 'SALE_IMPORT_CUSTOMER',
  DELETE_CUSTOMER: 'SALE_DELETE_CUSTOMER',
  SALE_ACTIVE_CUSTOMER: 'SALE_ACTIVE_CUSTOMER',
  SALE_INACTIVE_CUSTOMER: 'SALE_INACTIVE_CUSTOMER',

  // Boo
  CREATE_BOO: 'PRODUCE_CREATE_BOO',
  UPDATE_BOO: 'PRODUCE_UPDATE_BOO',
  DETAIL_BOO: 'PRODUCE_DETAIL_BOO',
  LIST_BOO: 'PRODUCE_LIST_BOO',
  DELETE_BOO: 'PRODUCE_DELETE_BOO',
  CONFIRM_BOO: 'PRODUCE_CONFIRM_BOO',
  REJECT_BOO: 'PRODUCE_REJECT_BOO',
  EXPORT_BOO: 'PRODUCE_EXPORT_BOO',

  // order-management
  LIST_ORDER_MANAGEMENT: 'FILE_WATCHER_LIST_ORDER',
  REPLY_ORDER_MANAGEMENT: 'FILE_WATCHER_REPLY_ORDER',
  DETAIL_ORDER_MANAGEMENT: 'FILE_WATCHER_DETAIL_ORDER',
  REJECT_ORDER_MANAGEMENT: 'FILE_WATCHER_CANCEL_ORDER',
  EXPORT_ORDER_MANAGEMENT: 'FILE_WATCHER_EXPORT_ORDER',
  IMPORT_ORDER_MANAGEMENT: 'FILE_WATCHER_IMPORT_REPLY_ORDER',

  // master-plan
  CREATE_MASTER_PLAN: 'PLAN_CREATE_MASTER_PLAN',
  UPDATE_MASTER_PLAN: 'PLAN_UPDATE_MASTER_PLAN',
  DETAIL_MASTER_PLAN: 'PLAN_DETAIL_MASTER_PLAN',
  DELETE_MASTER_PLAN: 'PLAN_DELETE_MASTER_PLAN',
  LIST_MASTER_PLAN: 'PLAN_LIST_MASTER_PLAN',
  SUBMIT_PENDING_MASTER_PLAN: 'PLAN_SUBMIT_PENDING_MASTER_PLAN',
  REJECT_MASTER_PLAN: 'PLAN_REJECT_MASTER_PLAN',
  CONFIRM_MASTER_PLAN: 'PLAN_CONFIRM_MASTER_PLAN',
  EXPORT_MASTER_PLAN: 'PLAN_EXPORT_MASTER_PLAN',
  PLAN_IMPORT_MASTER_PLAN: 'PLAN_IMPORT_MASTER_PLAN',
  // warehouse-stock
  LIST_WAREHOUSE_STOCK: 'ITEM_LIST_ITEM_STOCK_PLANNING_AVAILABLE_PERMISSION',
  EXPORT_WAREHOUSE_STOCK:
    'ITEM_EXPORT_ITEM_STOCK_PLANNING_AVAILABLE_PERMISSION',

  // return-material-request
  CREATE_RETURN_MATERIAL_REQUEST:
    'PRODUCTION_ORDER_CREATE_RETURN_MATERIAL_REQUEST',
  UPDATE_RETURN_MATERIAL_REQUEST:
    'PRODUCTION_ORDER_UPDATE_RETURN_MATERIAL_REQUEST',
  DETAIL_RETURN_MATERIAL_REQUEST:
    'PRODUCTION_ORDER_DETAIL_RETURN_MATERIAL_REQUEST',
  DELETE_RETURN_MATERIAL_REQUEST:
    'PRODUCTION_ORDER_DELETE_RETURN_MATERIAL_REQUEST',
  LIST_RETURN_MATERIAL_REQUEST: 'PRODUCTION_ORDER_LIST_RETURN_MATERIAL_REQUEST',
  REJECT_RETURN_MATERIAL_REQUEST:
    'PRODUCTION_ORDER_REJECT_RETURN_MATERIAL_REQUEST',
  SUBMIT_PENDING_RETURN_MATERIAL_REQUEST:
    'PRODUCTION_ORDER_SUBMIT_RETURN_MATERIAL_REQUEST',
  CONFIRM_RETURN_MATERIAL_REQUEST:
    'PRODUCTION_ORDER_CONFIRM_RETURN_MATERIAL_REQUEST',
  COMPLETE_RETURN_MATERIAL_REQUEST:
    'PRODUCTION_ORDER_COMPLETE_RETURN_MATERIAL_REQUEST',
  EXPORT_RETURN_MATERIAL_REQUEST:
    'PRODUCTION_ORDER_EXPORT_RETURN_MATERIAL_REQUEST',

  // production-order
  CREATE_PRODUCTION_ORDER: 'PRODUCTION_ORDER_CREATE_PRODUCTION_ORDER_EXPORT',
  UPDATE_PRODUCTION_ORDER: 'PRODUCTION_ORDER_UPDATE_PRODUCTION_ORDER_EXPORT',
  DETAIL_PRODUCTION_ORDER: 'PRODUCTION_ORDER_DETAIL_PRODUCTION_ORDER_EXPORT',
  DELETE_PRODUCTION_ORDER: 'PRODUCTION_ORDER_DELETE_PRODUCTION_ORDER_EXPORT',
  LIST_PRODUCTION_ORDER: 'PRODUCTION_ORDER_LIST_PRODUCTION_ORDER_EXPORT',
  REJECT_PRODUCTION_ORDER: 'PRODUCTION_ORDER_REJECT_PRODUCTION_ORDER_EXPORT',
  CONFIRM_PRODUCTION_ORDER: 'PRODUCTION_ORDER_CONFIRM_PRODUCTION_ORDER_EXPORT',
  APPROVE_PRODUCTION_ORDER: 'PRODUCTION_ORDER_APPROVE_PRODUCTION_ORDER_EXPORT',
  EXPORT_PRODUCTION_ORDER: 'PRODUCTION_ORDER_EXPORT_PRODUCTION_ORDER_EXPORT',

  // pro-import-request
  CREATE_PRO_IMPORT_REQUEST: 'PRODUCTION_ORDER_CREATE_PRODUCTION_ORDER_IMPORT',
  UPDATE_PRO_IMPORT_REQUEST: 'PRODUCTION_ORDER_UPDATE_PRODUCTION_ORDER_IMPORT',
  DETAIL_PRO_IMPORT_REQUEST: 'PRODUCTION_ORDER_DETAIL_PRODUCTION_ORDER_IMPORT',
  DELETE_PRO_IMPORT_REQUEST: 'PRODUCTION_ORDER_DELETE_PRODUCTION_ORDER_IMPORT',
  LIST_PRO_IMPORT_REQUEST: 'PRODUCTION_ORDER_LIST_PRODUCTION_ORDER_IMPORT',
  REJECT_PRO_IMPORT_REQUEST: 'PRODUCTION_ORDER_REJECT_PRODUCTION_ORDER_IMPORT',
  CONFIRM_PRO_IMPORT_REQUEST:
    'PRODUCTION_ORDER_CONFIRM_PRODUCTION_ORDER_IMPORT',
  EXPORT_PRO_IMPORT_REQUEST: 'PRODUCTION_ORDER_EXPORT_PRODUCTION_ORDER_IMPORT',

  // bill-sale-management
  SYNC_AS400_BILL_SALE: 'FILE_WATCHER_SYNC_UNIT_PRICE',
  UPDATE_BILL_SALE: 'FILE_WATCHER_UPDATE_UNIT_PRICE',
  LIST_BILL_SALE: 'FILE_WATCHER_LIST_UNIT_PRICE',
  DETAIL_BILL_SALE: 'FILE_WATCHER_DETAIL_UNIT_PRICE',
  EXPORT_BILL_SALE: 'FILE_WATCHER_EXPORT_UNIT_PRICE',

  // invoice-management
  UPDATE_INVOICE: 'INVOICE_UPDATE_INVOICE',
  DETAIL_INVOICE: 'INVOICE_DETAIL_INVOICE',
  LIST_INVOICE: 'INVOICE_LIST_INVOICE',
  APPROVE_INVOICE: 'INVOICE_APPROVE_INVOICE',
  COMPLETE_INVOICE: 'INVOICE_COMPLETE_INVOICE',
  SYNC_AS400_INVOICE: 'INVOICE_SYNC_INVOICE',
  EXPORT_INVOICE: 'INVOICE_EXPORT_INVOICE',
  EXPORT_PDF_INVOICE: 'INVOICE_EXPORT_PDF_INVOICE',
  EXPORT_VNACCS_INVOICE: 'INVOICE_EXPORT_VNACCS_INVOICE',

  // production-inventory
  LIST_PRODUCTION_INVENTORY: 'WAREHOUSE_LIST_SCENE_WAREHOUSE_DAILY_REPORT',
  EXPORT_PRODUCTION_INVENTORY: 'WAREHOUSE_EXPORT_SCENE_WAREHOUSE_DAILY_REPORT',

  // item-group-management
  ITEM_CREATE_ITEM_GROUP: 'ITEM_CREATE_ITEM_GROUP',
  ITEM_UPDATE_ITEM_GROUP: 'ITEM_UPDATE_ITEM_GROUP',
  ITEM_DELETE_ITEM_GROUP: 'ITEM_DELETE_ITEM_GROUP',
  ITEM_DETAIL_ITEM_GROUP: 'ITEM_DETAIL_ITEM_GROUP',
  ITEM_LIST_ITEM_GROUP: 'ITEM_LIST_ITEM_GROUP',
  ITEM_IMPORT_ITEM_GROUP: 'ITEM_IMPORT_ITEM_GROUP',
  ITEM_EXPORT_ITEM_GROUP: 'ITEM_EXPORT_ITEM_GROUP',

  // item-branch-management
  ITEM_CREATE_ITEM_BRANCH: 'ITEM_CREATE_ITEM_BRANCH',
  ITEM_UPDATE_ITEM_BRANCH: 'ITEM_UPDATE_ITEM_BRANCH',
  ITEM_DELETE_ITEM_BRANCH: 'ITEM_DELETE_ITEM_BRANCH',
  ITEM_DETAIL_ITEM_BRANCH: 'ITEM_DETAIL_ITEM_BRANCH',
  ITEM_LIST_ITEM_BRANCH: 'ITEM_LIST_ITEM_BRANCH',
  ITEM_ACTIVE_ITEM_BRANCH: 'ITEM_ACTIVE_ITEM_BRANCH',
  ITEM_INACTIVE_ITEM_BRANCH: 'ITEM_INACTIVE_ITEM_BRANCH',
  ITEM_IMPORT_ITEM_BRANCH: 'ITEM_IMPORT_ITEM_BRANCH',
  ITEM_EXPORT_ITEM_BRANCH: 'ITEM_EXPORT_ITEM_BRANCH',

  // item-type
  ITEM_CREATE_ITEM_TYPE: 'ITEM_CREATE_ITEM_TYPE',
  ITEM_UPDATE_ITEM_TYPE: 'ITEM_UPDATE_ITEM_TYPE',
  ITEM_DELETE_ITEM_TYPE: 'ITEM_DELETE_ITEM_TYPE',
  ITEM_DETAIL_ITEM_TYPE: 'ITEM_DETAIL_ITEM_TYPE',
  ITEM_LIST_ITEM_TYPE: 'ITEM_LIST_ITEM_TYPE',
  ITEM_IMPORT_ITEM_TYPE: 'ITEM_IMPORT_ITEM_TYPE',
  ITEM_EXPORT_ITEM_TYPE: 'ITEM_EXPORT_ITEM_TYPE',

  // item-unit
  ITEM_CREATE_ITEM_UNIT: 'ITEM_CREATE_ITEM_UNIT',
  ITEM_UPDATE_ITEM_UNIT: 'ITEM_UPDATE_ITEM_UNIT',
  ITEM_DELETE_ITEM_UNIT: 'ITEM_DELETE_ITEM_UNIT',
  ITEM_DETAIL_ITEM_UNIT: 'ITEM_DETAIL_ITEM_UNIT',
  ITEM_LIST_ITEM_UNIT: 'ITEM_LIST_ITEM_UNIT',
  ITEM_IMPORT_ITEM_UNIT: 'ITEM_IMPORT_ITEM_UNIT',
  ITEM_EXPORT_ITEM_UNIT: 'ITEM_EXPORT_ITEM_UNIT',

  //wms report export
  WMS_REPORT_DOWNLOAD_FILE_MENU: 'WMS_REPORT_DOWNLOAD_FILE_MENU',

  //item
  ITEM_CREATE_ITEM: 'ITEM_CREATE_ITEM',
  ITEM_UPDATE_ITEM: 'ITEM_UPDATE_ITEM',
  ITEM_REJECT_ITEM: 'ITEM_REJECT_ITEM',
  ITEM_CONFIRM_ITEM: 'ITEM_CONFIRM_ITEM',
  ITEM_IMPORT_ITEM: 'ITEM_IMPORT_ITEM',
  ITEM_DELETE_ITEM: 'ITEM_DELETE_ITEM',
  ITEM_DETAIL_ITEM: 'ITEM_DETAIL_ITEM',
  ITEM_LIST_ITEM: 'ITEM_LIST_ITEM',
  ITEM_ACTIVE_ITEM: 'ITEM_ACTIVE_ITEM',
  ITEM_INACTIVE_ITEM: 'ITEM_ACTIVE_INACTIVE_ITEM',

  // define-division
  LIST_DIVISION: 'COST_CENTER_LIST_DIVISION',
  CREATE_DIVISION: 'COST_CENTER_CREATE_DIVISION',
  UPDATE_DIVISION: 'COST_CENTER_UPDATE_DIVISION',
  DELETE_DIVISION: 'COST_CENTER_DELETE_DIVISION',
  DETAIL_DIVISION: 'COST_CENTER_DETAIL_DIVISION',
  IMPORT_DIVISION: 'COST_CENTER_IMPORT_DIVISION',
  EXPORT_DIVISION: 'COST_CENTER_EXPORT_DIVISION',
  ACTIVE_DIVISION: 'COST_CENTER_ACTIVE_DIVISION',
  INACTIVE_DIVISION: 'COST_CENTER_INACTIVE_DIVISION',
  APPROVE_DIVISION: 'COST_CENTER_APPROVE_DIVISION',

  // define-section
  LIST_SECTION: 'COST_CENTER_LIST_SECTION',
  CREATE_SECTION: 'COST_CENTER_CREATE_SECTION',
  UPDATE_SECTION: 'COST_CENTER_UPDATE_SECTION',
  DELETE_SECTION: 'COST_CENTER_DELETE_SECTION',
  DETAIL_SECTION: 'COST_CENTER_DETAIL_SECTION',
  IMPORT_SECTION: 'COST_CENTER_IMPORT_SECTION',
  EXPORT_SECTION: 'COST_CENTER_EXPORT_SECTION',
  CHANGE_STATUS_SECTION: 'COST_CENTER_CHANGE_STATUS_SECTION',

  // define-cost-center
  LIST_COST_CENTER: 'COST_CENTER_LIST_COST_CENTER',
  CREATE_COST_CENTER: 'COST_CENTER_CREATE_COST_CENTER',
  UPDATE_COST_CENTER: 'COST_CENTER_UPDATE_COST_CENTER',
  DELETE_COST_CENTER: 'COST_CENTER_DELETE_COST_CENTER',
  DETAIL_COST_CENTER: 'COST_CENTER_DETAIL_COST_CENTER',
  IMPORT_COST_CENTER: 'COST_CENTER_IMPORT_COST_CENTER',
  EXPORT_COST_CENTER: 'COST_CENTER_EXPORT_COST_CENTER',
  CHANGE_STATUS_COST_CENTER: 'COST_CENTER_CHANGE_STATUS_COST_CENTER',
  COST_CENTER_INACTIVE_SECTION: 'COST_CENTER_INACTIVE_SECTION',
  COST_CENTER_ACTIVE_SECTION: 'COST_CENTER_ACTIVE_SECTION',
  COST_CENTER_APPROVE_SECTION: 'COST_CENTER_APPROVE_SECTION',

  // define-holon
  LIST_HOLON: 'COST_CENTER_LIST_HOLON',
  CREATE_HOLON: 'COST_CENTER_CREATE_HOLON',
  UPDATE_HOLON: 'COST_CENTER_UPDATE_HOLON',
  DELETE_HOLON: 'COST_CENTER_DELETE_HOLON',
  DETAIL_HOLON: 'COST_CENTER_DETAIL_HOLON',
  IMPORT_HOLON: 'COST_CENTER_IMPORT_HOLON',
  EXPORT_HOLON: 'COST_CENTER_EXPORT_HOLON',
  CHANGE_STATUS_HOLON: 'COST_CENTER_CHANGE_STATUS_HOLON',

  // define-company
  LIST_COMPANY: 'USER_LIST_COMPANY',
  DETAIL_COMPANY: 'USER_DETAIL_COMPANY',

  // define-factory
  CREATE_FACTORY: 'USER_CREATE_FACTORY',
  UPDATE_FACTORY: 'USER_UPDATE_FACTORY',
  DELETE_FACTORY: 'USER_DELETE_FACTORY',
  DETAIL_FACTORY: 'USER_DETAIL_FACTORY',
  LIST_FACTORY: 'USER_LIST_FACTORY',
  IMPORT_FACTORY: 'USER_IMPORT_FACTORY',
  EXPORT_FACTORY: 'USER_EXPORT_FACTORY',

  // manufacturing-daily-report
  LIST_MANUFACTURING_DAILY_REPORT: 'PRODUCE_LIST_DAILY_MANUFACTURING_REPORT',
  DETAIL_MANUFACTURING_DAILY_REPORT:
    'PRODUCE_DETAIL_DAILY_MANUFACTURING_REPORT',
  EXPORT_MANUFACTURING_DAILY_REPORT:
    'PRODUCE_EXPORT_DAILY_MANUFACTURING_REPORT',

  // day-master-plan
  LIST_DAY_MASTER_PLAN: 'PLAN_GET_ITEM_SCHEDULE_LIST',
  UPDATE_DAY_MASTER_PLAN: 'PLAN_UPDATE_ITEM_SCHEDULE',

  // incoterm
  SALE_VIEW_LIST_INCOTERM: 'SALE_VIEW_LIST_INCOTERM',
  SALE_VIEW_DETAIL_INCOTERM: 'SALE_VIEW_DETAIL_INCOTERM',
  SALE_CREATE_INCOTERM: 'SALE_CREATE_INCOTERM',
  SALE_UPDATE_INCOTERM: 'SALE_UPDATE_INCOTERM',
  SALE_DELETE_INCOTERM: 'SALE_DELETE_INCOTERM',
  SALE_LOCK_INCOTERM: 'SALE_LOCK_INCOTERM',
  SALE_UNLOCK_INCOTERM: 'SALE_UNLOCK_INCOTERM',

  // pms-pucharse-request
  PMS_PURCHASE_REQUEST_LIST: 'PMS_PURCHASE_REQUEST_LIST',
  PMS_PURCHASE_REQUEST_DETAIL: 'PMS_PURCHASE_REQUEST_DETAIL',
  PMS_PURCHASE_REQUEST_CREATE: 'PMS_PURCHASE_REQUEST_CREATE',
  PMS_PURCHASE_REQUEST_UPDATE: 'PMS_PURCHASE_REQUEST_UPDATE',
  PMS_PURCHASE_REQUEST_WAIT_CONFIRM: 'PMS_PURCHASE_REQUEST_SUBMIT',
  PMS_PURCHASE_REQUEST_CONFIRM: 'PMS_PURCHASE_REQUEST_CONFIRM',
  PMS_PURCHASE_REQUEST_REJECT: 'PMS_PURCHASE_REQUEST_REJECT',
  PMS_PURCHASE_REQUEST_CANCEL: 'PMS_PURCHASE_REQUEST_CANCEL',
  PMS_PURCHASE_REQUEST_DELETE: 'PMS_PURCHASE_REQUEST_DELETE',
  PMS_PURCHASE_REQUEST_HISTORY: 'PMS_PURCHASE_REQUEST_HISTORY',
  PMS_PURCHASE_REQUEST_EXCHANGE: 'PMS_PURCHASE_REQUEST_EXCHANGE',
  PMS_PURCHASE_REQUEST_EXPORT: 'PMS_PURCHASE_REQUEST_EXPORT',
  PMS_PURCHASE_REQUEST_SUCCESS: 'PMS_PURCHASE_REQUEST_SUCCESS',

  // pms-pucharse-order
  PMS_LIST_PURCHASED_ORDER: 'PMS_LIST_PURCHASED_ORDER',
  PMS_DETAIL_PURCHASED_ORDER: 'PMS_DETAIL_PURCHASED_ORDER',
  PMS_CREATE_PURCHASED_ORDER: 'PMS_CREATE_PURCHASED_ORDER',
  PMS_UPDATE_PURCHASED_ORDER: 'PMS_UPDATE_PURCHASED_ORDER',
  PMS_ORDER_CONFIRM_PURCHASED_ORDER: 'PMS_ORDER_CONFIRM_PURCHASED_ORDER',
  PMS_CONFIRM_PURCHASED_ORDER: 'PMS_CONFIRM_PURCHASED_ORDER',
  PMS_REJECT_PURCHASED_ORDER: 'PMS_REJECT_PURCHASED_ORDER',
  PMS_CANCEL_PURCHASED_ORDER: 'PMS_CANCEL_PURCHASED_ORDER',
  PMS_PURCHASE_ORDER_SUCCESS: 'PMS_PURCHASE_ORDER_SUCCESS',
  PMS_DELETE_PURCHASED_ORDER: 'PMS_DELETE_PURCHASED_ORDER',
  PMS_PURCHASE_ORDER_WAIT_DELIVERY: 'PMS_PURCHASE_ORDER_WAIT_DELIVERY',
  PMS_PURCHASE_ORDER_HISTORY: 'PMS_PURCHASE_ORDER_HISTORY',
  PMS_PURCHASE_ORDER_EXPORT: 'PMS_PURCHASE_ORDER_EXPORT',
  PMS_PURCHASE_ORDER_SYNC: 'PMS_PURCHASE_ORDER_SYNC',
  PMS_SUBMIT_PURCHASED_ORDER: 'PMS_SUBMIT_PURCHASED_ORDER',

  // supplier
  MASTER_DATA_CREATE_VENDOR: 'MASTER_DATA_CREATE_VENDOR',
  MASTER_DATA_UPDATE_VENDOR: 'MASTER_DATA_UPDATE_VENDOR',
  MASTER_DATA_LIST_VENDOR: 'MASTER_DATA_LIST_VENDOR',
  MASTER_DATA_DELETE_VENDOR: 'MASTER_DATA_DELETE_VENDOR',
  MASTER_DATA_INACTIVE_VENDOR: 'MASTER_DATA_INACTIVE_VENDOR',
  MASTER_DATA_ACTIVE_VENDOR: 'MASTER_DATA_ACTIVE_VENDOR',
  MASTER_DATA_DETAIL_VENDOR: 'MASTER_DATA_DETAIL_VENDOR',
  MASTER_DATA_IMPORT_VENDOR: 'MASTER_DATA_IMPORT_VENDOR',
  MASTER_DATA_EXPORT_VENDOR: 'MASTER_DATA_EXPORT_VENDOR',

  // material inspection
  MASTER_DATA_CREATE_MATERIAL_INSPECTION:
    'MASTER_DATA_CREATE_MATERIAL_INSPECTION',
  MASTER_DATA_UPDATE_MATERIAL_INSPECTION:
    'MASTER_DATA_UPDATE_MATERIAL_INSPECTION',
  MASTER_DATA_DETAIL_MATERIAL_INSPECTION:
    'MASTER_DATA_DETAIL_MATERIAL_INSPECTION',
  MASTER_DATA_LIST_MATERIAL_INSPECTION: 'MASTER_DATA_LIST_MATERIAL_INSPECTION',
  MASTER_DATA_DELETE_MATERIAL_INSPECTION:
    'MASTER_DATA_DELETE_MATERIAL_INSPECTION',
  MASTER_DATA_INACTIVE_MATERIAL_INSPECTION:
    'MASTER_DATA_INACTIVE_MATERIAL_INSPECTION',
  MASTER_DATA_ACTIVE_MATERIAL_INSPECTION:
    'MASTER_DATA_ACTIVE_MATERIAL_INSPECTION',
  MASTER_DATA_IMPORT_MATERIAL_INSPECTION:
    'MASTER_DATA_IMPORT_MATERIAL_INSPECTION',
  MASTER_DATA_EXPORT_MATERIAL_INSPECTION:
    'MASTER_DATA_EXPORT_MATERIAL_INSPECTION',

  // evaluation criteria management
  MASTER_DATA_CREATE_EVALUATION_CRITERIA:
    'MASTER_DATA_CREATE_EVALUATION_CRITERIA',
  MASTER_DATA_UPDATE_EVALUATION_CRITERIA:
    'MASTER_DATA_UPDATE_EVALUATION_CRITERIA',
  MASTER_DATA_DETAIL_EVALUATION_CRITERIA:
    'MASTER_DATA_DETAIL_EVALUATION_CRITERIA',
  MASTER_DATA_LIST_EVALUATION_CRITERIA: 'MASTER_DATA_LIST_EVALUATION_CRITERIA',
  MASTER_DATA_DELETE_EVALUATION_CRITERIA:
    'MASTER_DATA_DELETE_EVALUATION_CRITERIA',
  MASTER_DATA_INACTIVE_EVALUATION_CRITERIA:
    'MASTER_DATA_INACTIVE_EVALUATION_CRITERIA',
  MASTER_DATA_ACTIVE_EVALUATION_CRITERIA:
    'MASTER_DATA_ACTIVE_EVALUATION_CRITERIA',

  // pms-invoice
  INVOICE_CREATE_PURCHASED_INVOICE: 'INVOICE_CREATE_PURCHASED_INVOICE',
  INVOICE_UPDATE_PURCHASED_INVOICE: 'INVOICE_UPDATE_PURCHASED_INVOICE',
  INVOICE_DETAIL_PURCHASED_INVOICE: 'INVOICE_DETAIL_PURCHASED_INVOICE',
  INVOICE_LIST_PURCHASED_INVOICE: 'INVOICE_LIST_PURCHASED_INVOICE',
  INVOICE_DELETE_PURCHASED_INVOICE: 'INVOICE_DELETE_PURCHASED_INVOICE',
  INVOICE_CANCEL_PURCHASED_INVOICE: 'INVOICE_CANCEL_PURCHASED_INVOICE',
  INVOICE_CONFIRM_REQUEST_PURCHASED_INVOICE:
    'INVOICE_CONFIRM_REQUEST_PURCHASED_INVOICE',
  INVOICE_REJECT_PURCHASED_INVOICE: 'INVOICE_REJECT_PURCHASED_INVOICE',
  INVOICE_CONFIRM_PURCHASED_INVOICE: 'INVOICE_CONFIRM_PURCHASED_INVOICE',
  INVOICE_SYNC_PURCHASED_INVOICE: 'INVOICE_SYNC_PURCHASED_INVOICE',
  INVOICE_EXPORT_PURCHASED_INVOICE: 'INVOICE_EXPORT_PURCHASED_INVOICE',

  // permission-by-role
  ADMIN_ROLE_ADMIN: 'PMS_DIVISION_ADMIN_ROLE_ADMIN_PERMS',
  WORKSHOP_ROLE_WORKSHOP_MANAGER:
    'PMS_DIVISION_WORKSHOP_ROLE_WORKSHOP_MANAGER_PERMS',
  WORKSHOP_ROLE_WORKSHOP_EMPLOYEE:
    'PMS_DIVISION_WORKSHOP_ROLE_WORKSHOP_EMPLOYEE_PERMS',
  WORKSHOP_ROLE_RECEIVER: 'PMS_DIVISION_WORKSHOP_ROLE_RECEIVER_PERMS',
  PURCHASE_ROLE_PURCHASE_MANAGER:
    'PMS_DIVISION_PURCHASE_ROLE_PURCHASE_MANAGER_PERMS',
  PURCHASE_ROLE_PURCHASE_EMPLOYEE:
    'PMS_DIVISION_PURCHASE_ROLE_PURCHASE_EMPLOYEE_PERMS',
  PURCHASE_ROLE_PURCHASE_ASSISTANT:
    'PMS_DIVISION_PURCHASE_ROLE_PURCHASE_ASSISTANT_PERMS',
  PURCHASE_ROLE_PURCHASE_SUPPORTER:
    'PMS_DIVISION_PURCHASE_ROLE_PURCHASE_SUPPORTER_PERMS',
  ACCOUNTING_ROLE_ACCOUNTING_MEMBER:
    'PMS_DIVISION_ACCOUNTING_ROLE_ACCOUNTING_MEMBER_PERMS',
  ACCOUNTING_ROLE_ACCOUNTING_CER_TEAM:
    'PMS_DIVISION_ACCOUNTING_ROLE_ACCOUNTING_CER_TEAM_PERMS',
  ACCOUNTING_ROLE_ACCOUNTING_NAVISION_TEAM:
    'PMS_DIVISION_ACCOUNTING_ROLE_ACCOUNTING_NAVISION_TEAM_PERMS',
  PMS_GLOBAL_DATA_VIEW_ALL: 'PMS_GLOBAL_DATA_VIEW_ALL_PERMS',

  //wmsx/receive-receipt
  REQUEST_CREATE_RECEIPT: 'REQUEST_CREATE_RECEIPT',
  REQUEST_UPDATE_RECEIPT: 'REQUEST_UPDATE_RECEIPT',
  REQUEST_DELETE_RECEIPT: 'REQUEST_DELETE_RECEIPT',
  REQUEST_DETAIL_RECEIPT: 'REQUEST_DETAIL_RECEIPT',
  REQUEST_LIST_RECEIPT: 'REQUEST_LIST_RECEIPT',
  REQUEST_CONFIRM_RECEIPT: 'REQUEST_CONFIRM_RECEIPT',
  //wmsx/warehouse-import-receipt
  TICKET_CREATE_RECEIPT_IMPORT: 'TICKET_CREATE_RECEIPT_IMPORT',
  TICKET_UPDATE_RECEIPT_IMPORT: 'TICKET_UPDATE_RECEIPT_IMPORT',
  TICKET_DELETE_RECEIPT_IMPORT: 'TICKET_DELETE_RECEIPT_IMPORT',
  TICKET_DETAIL_RECEIPT_IMPORT: 'TICKET_DETAIL_RECEIPT_IMPORT',
  TICKET_LIST_RECEIPT_IMPORT: 'TICKET_LIST_RECEIPT_IMPORT',
  TICKET_CONFIRM_RECEIPT_IMPORT: 'TICKET_CONFIRM_RECEIPT_IMPORT',
  TICKET_REJECT_RECEIPT_IMPORT: 'TICKET_REJECT_RECEIPT_IMPORT',
  TICKET_IMPORT_RECEIPT_IMPORT: 'TICKET_IMPORT_RECEIPT_IMPORT',
  TICKET_EXPORT_RECEIPT_IMPORT: 'TICKET_EXPORT_RECEIPT_IMPORT',
  TICKET_CREATE_RECEIPT_IMPORT_RECEIVE: 'TICKET_CREATE_RECEIPT_IMPORT_RECEIVE',
  TICKET_RETURN_RECEIPT_IMPORT: 'TICKET_RETURN_RECEIPT_IMPORT',
  TICKET_CREATE_RECEIPT_IMPORT_PUT_AWAY: 'TICKET_PUT_AWAY_ACTION',
  TICKET_PRINT_QR_TICKET_IMPORT: 'TICKET_PRINT_QR_TICKET_IMPORT',

  //wmsx/put-away
  TICKET_CREATE_TICKET_IMPORT_PUT_AWAY: 'TICKET_CREATE_TICKET_IMPORT_PUT_AWAY',

  //wmsx/finished-goods-serial-management
  CREATE_SERIAL_PERMISSION: 'CREATE_SERIAL_PERMISSION',
  LIST_SERIAL_PERMISSION: 'LIST_SERIAL_PERMISSION',
  DELETE_SERIAL_PERMISSION: 'DELETE_SERIAL_PERMISSION',
  SCAN_SERIAL_PERMISSION: 'SCAN_SERIAL_PERMISSION',

  //wmsx/request-import
  REQUEST_CREATE_REQUEST_ORDER: 'REQUEST_CREATE_REQUEST_ORDER',
  REQUEST_UPDATE_REQUEST_ORDER: 'REQUEST_UPDATE_REQUEST_ORDER',
  REQUEST_DELETE_REQUEST_ORDER: 'REQUEST_DELETE_REQUEST_ORDER',
  REQUEST_DETAIL_REQUEST_ORDER: 'REQUEST_DETAIL_REQUEST_ORDER',
  REQUEST_LIST_REQUEST_ORDER: 'REQUEST_LIST_REQUEST_ORDER',
  REQUEST_CONFIRM_REQUEST_ORDER: 'REQUEST_CONFIRM_REQUEST_ORDER',
  REQUEST_REJECT_REQUEST_ORDER: 'REQUEST_REJECT_REQUEST_ORDER',
  REQUEST_CLOSE_REQUEST_ORDER: 'REQUEST_CLOSE_REQUEST_ORDER',
  REQUEST_IMPORT_REQUEST_ORDER_GROUPEXPORT_EXCEL:
    'REQUEST_IMPORT_REQUEST_ORDER_GROUPEXPORT_EXCEL',
  REQUEST_IMPORT_REQUEST_ORDER_GROUPIMPORT_EXCEL:
    'REQUEST_IMPORT_REQUEST_ORDER_GROUPIMPORT_EXCEL',

  //wmsx/request-export
  REQUEST_EXPORT_REQUEST_ORDER_GROUPCREATE:
    'REQUEST_EXPORT_REQUEST_ORDER_GROUPCREATE',
  REQUEST_EXPORT_REQUEST_ORDER_GROUPUPDATE:
    'REQUEST_EXPORT_REQUEST_ORDER_GROUPUPDATE',
  REQUEST_EXPORT_REQUEST_ORDER_GROUPDELETE:
    'REQUEST_EXPORT_REQUEST_ORDER_GROUPDELETE',
  REQUEST_EXPORT_REQUEST_ORDER_GROUPGET_DETAIL:
    'REQUEST_EXPORT_REQUEST_ORDER_GROUPGET_DETAIL',
  REQUEST_EXPORT_REQUEST_ORDER_GROUPGET_LIST:
    'REQUEST_EXPORT_REQUEST_ORDER_GROUPGET_LIST',
  REQUEST_EXPORT_REQUEST_ORDER_GROUPCONFIRM:
    'REQUEST_EXPORT_REQUEST_ORDER_GROUPCONFIRM',
  REQUEST_EXPORT_REQUEST_ORDER_GROUPREJECT:
    'REQUEST_EXPORT_REQUEST_ORDER_GROUPREJECT',
  REQUEST_EXPORT_REQUEST_ORDER_GROUPCLOSE:
    'REQUEST_EXPORT_REQUEST_ORDER_GROUPCLOSE',

  // wmsx/warehouse-export-receipt
  TICKET_CREATE_TICKET: 'TICKET_CREATE_TICKET',
  TICKET_UPDATE_TICKET: 'TICKET_UPDATE_TICKET',
  TICKET_DELETE_TICKET: 'TICKET_DELETE_TICKET',
  TICKET_DETAIL_TICKET: 'TICKET_DETAIL_TICKET',
  TICKET_LIST_TICKET: 'TICKET_LIST_TICKET',
  TICKET_RETURN_TICKET_EXPORT: 'TICKET_RETURN_TICKET_EXPORT',
  TICKET_RECEIVE_TICKET_IMPORT: 'TICKET_RECEIVE_TICKET_IMPORT',
  TICKET_CONFIRM_TICKET_EXPORT: 'TICKET_CONFIRM_TICKET_EXPORT',
  TICKET_CONFIRM_TICKET_IMPORT: 'TICKET_CONFIRM_TICKET_IMPORT',
  TICKET_REJECT_TICKET_EXPORT: 'TICKET_REJECT_TICKET_EXPORT',
  TICKET_PICK_UP_TICKET_EXPORT: 'TICKET_PICK_UP_ACTION',
  TICKET_EXPORTED_TICKET_EXPORT: 'TICKET_EXPORTED_TICKET_EXPORT',
  TICKET_PACKING_LIST_TICKET_EXPORT: 'TICKET_PACKING_LIST_TICKET_EXPORT',

  // export receipt
  TICKET_RECEIPT_EXPORT_GROUP_CREATE: 'TICKET_RECEIPT_EXPORT_GROUP_CREATE',
  TICKET_RECEIPT_EXPORT_GROUP_UPDATE: 'TICKET_RECEIPT_EXPORT_GROUP_UPDATE',
  TICKET_RECEIPT_EXPORT_GROUP_DELETE: 'TICKET_RECEIPT_EXPORT_GROUP_DELETE',
  TICKET_RECEIPT_EXPORT_GROUP_DETAIL: 'TICKET_RECEIPT_EXPORT_GROUP_DETAIL',
  TICKET_RECEIPT_EXPORT_GROUP_LIST: 'TICKET_RECEIPT_EXPORT_GROUP_LIST',
  TICKET_RECEIPT_EXPORT_GROUP_CONFIRM: 'TICKET_RECEIPT_EXPORT_GROUP_CONFIRM',
  TICKET_RECEIPT_EXPORT_GROUP_REJECT: 'TICKET_RECEIPT_EXPORT_GROUP_REJECT',
  TICKET_RECEIPT_EXPORT_GROUP_EXPORT: 'TICKET_RECEIPT_EXPORT_GROUP_EXPORT',
  TICKET_RECEIPT_EXPORT_GROUP_IMPORT: 'TICKET_RECEIPT_EXPORT_GROUP_IMPORT',
  TICKET_RECEIPT_EXPORT_GROUP_RETURN: 'TICKET_RECEIPT_EXPORT_GROUP_RETURN',
  TICKET_RECEIPT_EXPORT_GROUP_EXPORTED: 'TICKET_RECEIPT_EXPORT_GROUP_EXPORTED',
  TICKET_RECEIPT_EXPORT_GROUP_PICK_UP: 'TICKET_RECEIPT_EXPORT_GROUP_PICK_UP',
  TICKET_RECEIPT_EXPORT_GROUP_PACKING_LIST:
    'TICKET_RECEIPT_EXPORT_GROUP_PACKING_LIST',
  TICKET_RECEIPT_EXPORT_GROUP_CANCEL: 'TICKET_RECEIPT_EXPORT_GROUP_CANCEL',

  // request order group
  REQUEST_IMPORT_REQUEST_ORDER_GROUPCREATE:
    'REQUEST_IMPORT_REQUEST_ORDER_GROUPCREATE',
  REQUEST_IMPORT_REQUEST_ORDER_GROUPUPDATE:
    'REQUEST_IMPORT_REQUEST_ORDER_GROUPUPDATE',
  REQUEST_IMPORT_REQUEST_ORDER_GROUPDELETE:
    'REQUEST_IMPORT_REQUEST_ORDER_GROUPDELETE',
  REQUEST_IMPORT_REQUEST_ORDER_GROUPGET_DETAIL:
    'REQUEST_IMPORT_REQUEST_ORDER_GROUPGET_DETAIL',
  REQUEST_IMPORT_REQUEST_ORDER_GROUPGET_LIST:
    'REQUEST_IMPORT_REQUEST_ORDER_GROUPGET_LIST',
  REQUEST_IMPORT_REQUEST_ORDER_GROUPCONFIRM:
    'REQUEST_IMPORT_REQUEST_ORDER_GROUPCONFIRM',
  REQUEST_IMPORT_REQUEST_ORDER_GROUPREJECT:
    'REQUEST_IMPORT_REQUEST_ORDER_GROUPREJECT',
  REQUEST_IMPORT_REQUEST_ORDER_GROUPCLOSE:
    'REQUEST_IMPORT_REQUEST_ORDER_GROUPCLOSE',
  REQUEST_IMPORT_REQUEST_ORDER_GROUPPRINT_QR:
    'REQUEST_IMPORT_REQUEST_ORDER_GROUPPRINT_QR',
  REQUEST_IMPORT_REQUEST_ORDER_GROUPINPROGRESS:
    'REQUEST_IMPORT_REQUEST_ORDER_GROUPINPROGRESS',
  REQUEST_IMPORT_REQUEST_ORDER_GROUPPENDING:
    'REQUEST_IMPORT_REQUEST_ORDER_GROUPPENDING',
  REQUEST_IMPORT_REQUEST_ORDER_GROUPRETURN:
    'REQUEST_IMPORT_REQUEST_ORDER_GROUPRETURN',
  REQUEST_IMPORT_REQUEST_ORDER_GROUPPRINT_SUMMARY_PACKING_INSPECTION_LIST:
    'REQUEST_IMPORT_REQUEST_ORDER_GROUPPRINT_SUMMARY_PACKING_INSPECTION_LIST',
  REQUEST_IMPORT_REQUEST_ORDER_GROUPPRINT_DETAILED_PACKING_INSPECTION_LIST:
    'REQUEST_IMPORT_REQUEST_ORDER_GROUPPRINT_DETAILED_PACKING_INSPECTION_LIST',
  //wmsx/inventory-allocation
  CREATE_INVENTORY_ALLOCATION:
    'WAREHOUSE_WAREHOUSE_BUSINESS_WAREHOUSE_MAPPING_GROUP_CREATE',
  UPDATE_INVENTORY_ALLOCATION:
    'WAREHOUSE_WAREHOUSE_BUSINESS_WAREHOUSE_MAPPING_GROUP_UPDATE',
  DELETE_INVENTORY_ALLOCATION:
    'WAREHOUSE_WAREHOUSE_BUSINESS_WAREHOUSE_MAPPING_GROUP_DELETE',
  DETAIL_INVENTORY_ALLOCATION:
    'WAREHOUSE_WAREHOUSE_BUSINESS_WAREHOUSE_MAPPING_GROUP_GET_DETAIL',
  LIST_INVENTORY_ALLOCATION:
    'WAREHOUSE_WAREHOUSE_BUSINESS_WAREHOUSE_MAPPING_GROUP_GET_LIST',

  //transfer-item
  LIST_LOCATOR_TRANSFER: 'LIST_LOCATOR_TRANSFER',
  SUBMIT_LOCATOR_TRANSFER: 'SUBMIT_LOCATOR_TRANSFER',

  // picking receipt
  TICKET_RECEIPT_PICKING_GROUP_CREATE: 'TICKET_RECEIPT_PICKING_GROUP_CREATE',
  TICKET_RECEIPT_PICKING_GROUP_UPDATE: 'TICKET_RECEIPT_PICKING_GROUP_UPDATE',
  TICKET_RECEIPT_PICKING_GROUP_DELETE: 'TICKET_RECEIPT_PICKING_GROUP_DELETE',
  TICKET_RECEIPT_PICKING_GROUP_DETAIL: 'TICKET_RECEIPT_PICKING_GROUP_DETAIL',
  TICKET_RECEIPT_PICKING_GROUP_LIST: 'TICKET_RECEIPT_PICKING_GROUP_LIST',
  TICKET_RECEIPT_PICKING_GROUP_CONFIRM: 'TICKET_RECEIPT_PICKING_GROUP_CONFIRM',
  TICKET_RECEIPT_PICKING_GROUP_ASSIGN: 'TICKET_RECEIPT_PICKING_GROUP_ASSIGN',

  // invetory-order
  FORMULA_MANAGEMENT_CREATE_INVENTORY_ORDER:
    'FORMULA_MANAGEMENT_CREATE_INVENTORY_ORDER',
  FORMULA_MANAGEMENT_UPDATE_INVENTORY_ORDER:
    'FORMULA_MANAGEMENT_UPDATE_INVENTORY_ORDER',
  FORMULA_MANAGEMENT_DELETE_INVENTORY_ORDER:
    'FORMULA_MANAGEMENT_DELETE_INVENTORY_ORDER',
  FORMULA_MANAGEMENT_CONFIRM_INVENTORY_ORDER:
    'FORMULA_MANAGEMENT_CONFIRM_INVENTORY_ORDER',
  FORMULA_MANAGEMENT_REJECT_INVENTORY_ORDER:
    'FORMULA_MANAGEMENT_REJECT_INVENTORY_ORDER',
  FORMULA_MANAGEMENT_LIST_INVENTORY_ORDER:
    'FORMULA_MANAGEMENT_LIST_INVENTORY_ORDER',
  FORMULA_MANAGEMENT_DETAIL_INVENTORY_ORDER:
    'FORMULA_MANAGEMENT_DETAIL_INVENTORY_ORDER',

  // inventory plan
  FORMULA_MANAGEMENT_CREATE_INVENTORY_PLAN:
    'FORMULA_MANAGEMENT_CREATE_INVENTORY_PLAN',
  FORMULA_MANAGEMENT_UPDATE_INVENTORY_PLAN:
    'FORMULA_MANAGEMENT_UPDATE_INVENTORY_PLAN',
  FORMULA_MANAGEMENT_DELETE_INVENTORY_PLAN:
    'FORMULA_MANAGEMENT_DELETE_INVENTORY_PLAN',
  FORMULA_MANAGEMENT_CONFIRM_INVENTORY_PLAN:
    'FORMULA_MANAGEMENT_CONFIRM_INVENTORY_PLAN',
  FORMULA_MANAGEMENT_REJECT_INVENTORY_PLAN:
    'FORMULA_MANAGEMENT_REJECT_INVENTORY_PLAN',
  FORMULA_MANAGEMENT_LIST_INVENTORY_PLAN:
    'FORMULA_MANAGEMENT_LIST_INVENTORY_PLAN',
  FORMULA_MANAGEMENT_DETAIL_INVENTORY_PLAN:
    'FORMULA_MANAGEMENT_DETAIL_INVENTORY_PLAN',

  // inventory ticket
  FORMULA_MANAGEMENT_LIST_INVENTORY_TICKET:
    'FORMULA_MANAGEMENT_LIST_INVENTORY_TICKET',
  FORMULA_MANAGEMENT_DETAIL_INVENTORY_TICKET:
    'FORMULA_MANAGEMENT_DETAIL_INVENTORY_TICKET',
  FORMULA_MANAGEMENT_DELETE_INVENTORY_TICKET:
    'FORMULA_MANAGEMENT_DELETE_INVENTORY_TICKET',
  FORMULA_MANAGEMENT_EXECUTE_INVENTORY_TICKET:
    'FORMULA_MANAGEMENT_EXECUTE_INVENTORY_TICKET',
  FORMULA_MANAGEMENT_STOP_INVENTORY_TICKET:
    'FORMULA_MANAGEMENT_STOP_INVENTORY_TICKET',
  FORMULA_MANAGEMENT_LIST_TRANSACTION_INVENTORY_TICKET:
    'FORMULA_MANAGEMENT_LIST_TRANSACTION_INVENTORY_TICKET',
  FORMULA_MANAGEMENT_CONFIRM_FINISH_INVENTORY_TICKET:
    'FORMULA_MANAGEMENT_CONFIRM_FINISH_INVENTORY_TICKET',
  FORMULA_MANAGEMENT_CONFIRM_RESULT_INVENTORY_TICKET:
    'FORMULA_MANAGEMENT_CONFIRM_RESULT_INVENTORY_TICKET',
  FORMULA_MANAGEMENT_REJECT_RESULT_INVENTORY_TICKET:
    'FORMULA_MANAGEMENT_REJECT_RESULT_INVENTORY_TICKET',

  //goods-storage-category
  MASTER_DATA_CREATE_ITEM_STORAGE: 'MASTER_DATA_CREATE_ITEM_STORAGE',
  MASTER_DATA_UPDATE_ITEM_STORAGE: 'MASTER_DATA_UPDATE_ITEM_STORAGE',
  MASTER_DATA_DETAIL_ITEM_STORAGE: 'MASTER_DATA_DETAIL_ITEM_STORAGE',
  MASTER_DATA_LIST_ITEM_STORAGE: 'MASTER_DATA_LIST_ITEM_STORAGE',
  MASTER_DATA_DELETE_ITEM_STORAGE: 'MASTER_DATA_DELETE_ITEM_STORAGE',
  MASTER_DATA_INACTIVE_ITEM_STORAGE: 'MASTER_DATA_INACTIVE_ITEM_STORAGE',
  MASTER_DATA_ACTIVE_ITEM_STORAGE: 'MASTER_DATA_ACTIVE_ITEM_STORAGE',
  MASTER_DATA_IMPORT_ITEM_STORAGE: 'MASTER_DATA_IMPORT_ITEM_STORAGE',
  MASTER_DATA_EXPORT_ITEM_STORAGE: 'MASTER_DATA_EXPORT_ITEM_STORAGE',

  //cont-package-status
  MASTER_DATA_CREATE_PACKAGE_STATUS: 'MASTER_DATA_CREATE_PACKAGE_STATUS',
  MASTER_DATA_UPDATE_PACKAGE_STATUS: 'MASTER_DATA_UPDATE_PACKAGE_STATUS',
  MASTER_DATA_DETAIL_PACKAGE_STATUS: 'MASTER_DATA_DETAIL_PACKAGE_STATUS',
  MASTER_DATA_LIST_PACKAGE_STATUS: 'MASTER_DATA_LIST_PACKAGE_STATUS',
  MASTER_DATA_DELETE_PACKAGE_STATUS: 'MASTER_DATA_DELETE_PACKAGE_STATUS',
  MASTER_DATA_INACTIVE_PACKAGE_STATUS: 'MASTER_DATA_INACTIVE_PACKAGE_STATUS',
  MASTER_DATA_ACTIVE_PACKAGE_STATUS: 'MASTER_DATA_ACTIVE_PACKAGE_STATUS',
  MASTER_DATA_IMPORT_PACKAGE_STATUS: 'MASTER_DATA_IMPORT_PACKAGE_STATUS',
  MASTER_DATA_EXPORT_PACKAGE_STATUS: 'MASTER_DATA_EXPORT_PACKAGE_STATUS',

  // rotation-level-management
  MASTER_DATA_CREATE_TRANSFER_LEVEL: 'MASTER_DATA_CREATE_TRANSFER_LEVEL',
  MASTER_DATA_UPDATE_TRANSFER_LEVEL: 'MASTER_DATA_UPDATE_TRANSFER_LEVEL',
  MASTER_DATA_DETAIL_TRANSFER_LEVEL: 'MASTER_DATA_DETAIL_TRANSFER_LEVEL',
  MASTER_DATA_LIST_TRANSFER_LEVEL: 'MASTER_DATA_LIST_TRANSFER_LEVEL',
  MASTER_DATA_DELETE_TRANSFER_LEVEL: 'MASTER_DATA_DELETE_TRANSFER_LEVEL',
  MASTER_DATA_INACTIVE_TRANSFER_LEVEL: 'MASTER_DATA_INACTIVE_TRANSFER_LEVEL',
  MASTER_DATA_ACTIVE_TRANSFER_LEVEL: 'MASTER_DATA_ACTIVE_TRANSFER_LEVEL',
  MASTER_DATA_IMPORT_TRANSFER_LEVEL: 'MASTER_DATA_IMPORT_TRANSFER_LEVEL',
  MASTER_DATA_EXPORT_TRANSFER_LEVEL: 'MASTER_DATA_EXPORT_TRANSFER_LEVEL',

  //system access history
  DATASYNC_LIST_AUTH_LOG: 'DATASYNC_LIST_AUTH_LOG',

  //maintensystem
  USER_CHANGE_STATUS_MAINTENANCE_SYSTEM:
    'USER_CHANGE_STATUS_MAINTENANCE_SYSTEM',
  DEVICE_STATUS_DASHBOARD: 'MMS_DEVICE_DASHBOARD_STATUS',

}
