export const SALE_TYPE_TEMPLATE = {
  SALE_ORDER: 4,
  EXPORT_DATE: 7,
  REASON: 5,
  CUSTOMER: 6,
}

export const SALE_TYPE_IMPORT = {
  CUSTOMER: 1,
  EXPORT_DATE: 2,
}

export const SALE_TYPE_EXPORT = {
  ORDER: 2,
  REASON: 4,
  BILL_SALE_MANAGEMENT: 12,
}

export const WAREHOUSE_TYPE_EXPORT = {
  PRODUCTION_INVENTORY: 1,
}

export const MMS_TYPE_EXPORT = {
  PRODUCTIVITY_DEVICE: 33,
  JOB: 19,
}

export const MMS_TYPE_IMPORT = {
  PRODUCTIVITY_DEVICE: 32,
}

export const PRODUCES_TYPE_TEMPLATE = {
  ROUTING: 1,
  PRODUCING_STEP: 3,
  ERROR_CODE: 4,
  PRODUCTION_LINE: 5,
  PLANT: 6,
  MOLD: 7,
  TEMPLATE: 8,
  USER_MANAGEMENT: 9,
  CHECK_SHEET: 10,
  MAINTENANCE_TEAM: 11,
  DEVICE_GROUP: 12,
  DEVICE: 13,
  ITEM_NORM: 14,
  PRODUCTIVITY_DEVICE: 16,
  PRODUCTIVITY_DEVICE_TABLE: 17,
  BOM_IMPORT_EXPORT_TABLE: 18,
  REPAIR_REQUEST: 19,
  BOO: 19,
  BLUE_PRINT: 20,
}

export const PRODUCES_TYPE_EXPORT = {
  ROUTING: 1,
  PRODUCING_STEP: 2,
  ERROR_CODE: 4,
  PRODUCTION_LINE: 9,
  ITEM_NORM_VERSION: 12,
  MOLD: 13,
  MANUFACTURING_ORDER: 14,
  BOO: 15,
  MANUFACTURING_DAILY_REPORT: 16,
  BOM_IMPORT_EXPORT: 17,
  BOM_IMPORT_EXPORT_DETAIL: 18,
  BLUE_PRINT_EXPORT: 20,
  MATERIAL_INSPECTION: 3,
}

export const PRODUCES_TYPE_IMPORT = {
  ITEM_NORM: 4,
  BOM_IMPORT_EXPORT_TABLE: 5,
  BOO: 6,
}

export const PLANS_TYPE_TEMPLATE = {
  MONTH_MASTER_PLAN: 1,
  EXPORT_PLAN: 1,
}

export const PLANS_TYPE_EXPORT = {
  MONTH_MASTER_PLAN: 1,
  EXPORT_PLAN: 1,
}

export const PRODUCTION_ORDER_TYPE_IMPORT = {
  PRODUCTION_ORDER: 1,
}

export const PRODUCTION_ORDER_TYPE_EXPORT = {
  PRO_IMPORT_REQUEST: 1,
  PRODUCTION_ORDER: 2,
  RETURN_MATERIAL_REQUEST: 3,
}

export const SALES_TYPE_EXPORT = {
  ORDER: 1,
}

export const USER_TYPE_EXPORT = {
  USER_MANAGEMENT: 3,
  DEPARTMENT_SETTING: 5,
}

export const USER_TYPE_TEMPLATE = {
  DEPARTMENT_SETTING: 3,
  EMAIL_NOTIFICATION: 4,
}

export const FILE_WATCHER_TYPE_EXPORT = {
  ORDER: 1,
  UNIT_PRICE: 2,
  NOT_EXPORT_ON_TIME_ORDER_REPORT: 3,
}

export const FILE_WATCHER_TYPE_TEMPLATE = {
  ORDER: 1,
}

export const SALE_ORDER_INSTRUCTION_TYPE_EXPORT = {
  SHIPPING_INSTRUCTION_PDF: 2,
  SHIPPING_INSTRUCTION: 3,
}

export const ITEMS_TYPE_EXPORT = {
  WAREHOUSE_STOCK: 7,
  ITEM_LINE_MANAGEMENT: 1,
  UNIT_PRICE_STATUS_STATISTIC: 9,
  MANUFACTURING_EXPORT_REPORT: 10,
  ITEM_BRANCH_MANAGEMENT: 2,
}

export const ITEMS_TYPE_TEMPLATE = {
  ITEM_UNIT: 3,
  ITEM_LINE_MANAGEMENT: 6,
  ITEM_BRANCH_MANAGEMENT: 7,
  ITEM_GROUP_MANAGEMENT: 1,
}

export const COST_CENTER_TYPE_TEMPLATE = {
  COST_CENTER: 1,
  HOLON: 2,
  SECTION: 3,
  DIVISION: 4,
}

export const COST_CENTER_TYPE_EXPORT = {
  DIVISION: 1,
  SECTION: 2,
  COST_CENTER: 3,
  HOLON: 4,
}

export const HRM_TYPE_EXPORT = {
  HOUR_SALARY_COST: 1,
  EMPLOYEE_MANAGEMENT: 6,
}

export const MESX_REPORT_TYPE_EXPORT = {
  QUALITY_REPORT: 1,
}

export const DEVICE_TYPE_EXPORT = {
  PRODUCTIVITY_DEVICE: 1,
}

export const DEVICE_TYPE_TEMPLATE = {
  PRODUCTIVITY_DEVICE: 1,
}

export const QUOTATION_TYPE_TEMPLATE = {
  IR: 1,
}

export const QUOTATION_TYPE_IMPORT = {
  IR: 1,
}

export const MASTER_DATA_TYPE_EXPORT = {
  VENDOR: 2,
  MATERIAL_INSPECTION: 3,
  ERROR_CODE: 4,
  REASON: 5,
}

export const MASTER_DATA_TYPE_TEMPLATE = {
  VENDOR: 2,
  MATERIAL_INSPECTION: 3,
  ERROR_CODE: 4,
  REASON: 5,
}
